hmLoadTopic({
hmKeywords:"Activities,Activities Events,Event,Event Management",
hmTitle:"Events",
hmDescription:"Devman\'s Event management module simplifies this difficult and time-consuming job. This built in tool takes the trouble out of the entire process.",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"devmanfunction.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > Workflow",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Events<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Devman\'s <a href=\"javascript:void(0);\" data-target=\"gsyeventmanagement.js\" class=\"popuplink\">Event management<\/a> module simplifies this difficult and time-consuming job. This built in tool takes the trouble out of the entire process.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">By using <a href=\"actmailshottemplate.html\" class=\"topiclink\">mailshot templates<\/a>, you can send attractive, colourful personalised invitations to your guests. &nbsp;Specific invitation and seating card layouts with your company logo on can be designed and incorporated for you by the Kidz Africa Team. &nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Once you have invited your guests you can manage those who have accepted, declined and attended. &nbsp; <\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Using Development Manager\'s reporting function you can print various types of guest lists and name tags.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Depending on your organisation\'s requirements you may wish to allocate parking, reserve seats, include partners etc. &nbsp;You may also want to include dietary requirements. &nbsp;If activated, the dietary requirements flag is available on the person profile page, and you can print a dietary requirements list via the Manage Guest List screen. &nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">If you would like to use any of these features, please discuss with your Kidz Africa Relationship Manager.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">This Help sections provides help on how to <a href=\"acteventadd.html\" class=\"topiclink\">add an event<\/a>, <a href=\"acteventtrack.html\" class=\"topiclink\">manage it<\/a> and print out a <a href=\"acteventprintgl.html\" class=\"topiclink\">guest list<\/a> and <a href=\"acteventprintnt.html\" class=\"topiclink\">names tags<\/a>.<\/span><\/p>\n\r"
})
