hmLoadTopic({
hmKeywords:"Activities",
hmTitle:"Activities",
hmDescription:"The system allows you to carry out a number of activities and also to track their progress. This includes letters, events, mailshots, progress reports and interactions.",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"devmanfunction.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > Workflow",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Activities<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">The system allows you to carry out a number of activities and also to track their progress. This includes <a href=\"actletter.html\" class=\"topiclink\">letters<\/a>, <a href=\"actevent.html\" class=\"topiclink\">events<\/a>, <a href=\"actmailshot.html\" class=\"topiclink\">mailshots<\/a>, progress reports and <a href=\"actinteraction.html\" class=\"topiclink\">interactions<\/a>.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">By setting up reminders, you can keep track of which activities are due and which have been completed. Letter reminders are set up as part of the project life cycle. For example, once you have captured a new proposal, you may receive a reminder in My inbox on the home page, reminding you to send an acknowledgement letter.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 2.3750rem 0 2.3750rem;\"><table style=\"border:none;border-spacing:0;padding:0;line-height: 1.38;\"><tr style=\"vertical-align:baseline\"><td style=\"border:none;padding:0;width:1.1250rem\"><img id=\"toggle0186a1_ICON\" class=\"dropdown-toggle-icon\" alt=\"hmtoggle_plus0\" style=\"margin:0;width:0.5625rem;height:0.5625rem;border:none\" src=\".\/images\/hmtoggle_plus0.gif\"\/><\/td><td style=\"border:none;padding:0\"><span class=\"f_KidzNormalIndent\"><a id=\"toggle0186a1_LINK\" class=\"dropdown-toggle\" href=\"javascript:void(0)\" data-type=\"dropdown\" data-state=\"0\" data-icon=\"toggle0186a1_ICON\" data-src0=\".\/images\/hmtoggle_plus0.gif\" data-src1=\".\/images\/hmtoggle_plus1.gif\">Click here to view<\/a><\/span><\/td><\/tr><\/table><\/div>\n\r<div id=\"toggle0186a1\" class=\"dropdown-toggle-body\" style=\"text-align: left; text-indent: 0; line-height: 1.38; padding: 0 0 0 0; margin: 0 2.3750rem 0 2.3750rem;display:none\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Normal\"><img alt=\"wpActivitiesDue\" style=\"margin:0;width:24.5625rem;height:10.6875rem;border:none\" src=\".\/images\/wpactivitiesdue.png\"\/><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r"
})
