hmLoadTopic({
hmKeywords:"",
hmTitle:"Commitments",
hmDescription:"Overview    Topics  \tAdd a commitment",
hmPrevLink:"budget.html",
hmNextLink:"pledges.html",
hmParentLink:"expenditure.html",
hmBreadCrumbs:"<a href=\"devmanfunction.html\">DevMan functions<\/a> &gt; <a href=\"devfinance.html\">Finance<\/a> &gt; <a href=\"expenditure.html\">Expenditure<\/a>",
hmTitlePath:"DevMan functions > Finance > Expenditure > Commitments",
hmHeader:"<p class=\"p_KidzHeader1New\"><span class=\"f_KidzHeader1New\">Commitments<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzHeader12New\"><span class=\"f_KidzHeader12New\">Overview<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzHeader12\"><span class=\"f_KidzHeader12\">Topics<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 2.3750rem 0 2.3750rem;\"><table style=\"border:none;border-spacing:0;padding:0;line-height: 1.38;\"><tr style=\"vertical-align:baseline\"><td style=\"border:none;padding:0;width:1.1250rem\"><img id=\"toggle0186a1_ICON\" class=\"dropdown-toggle-icon\" alt=\"Add a single or recurring installment plan for your beneficiaries\" title=\"Add a single or recurring installment plan for your beneficiaries\" style=\"margin:0;width:0.5625rem;height:0.5625rem;border:none\" src=\".\/images\/hmtoggle_arrow0.gif\"\/><\/td><td style=\"border:none;padding:0\"><span class=\"f_KidzNormalIndent\"><a id=\"toggle0186a1_LINK\" class=\"dropdown-toggle\" title=\"Add a single or recurring installment plan for your beneficiaries\" href=\"javascript:void(0)\" data-type=\"dropdown\" data-state=\"0\" data-icon=\"toggle0186a1_ICON\" data-src0=\".\/images\/hmtoggle_arrow0.gif\" data-src1=\".\/images\/hmtoggle_arrow1.gif\">Add a commitment<\/a><\/span><\/td><\/tr><\/table><\/div>\n\r<div id=\"toggle0186a1\" class=\"dropdown-toggle-body\" style=\"text-align: left; line-height: 1.38; padding: 0 0 0 0; margin: 0 2.3750rem 0 3.5000rem;display:none\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_KidzNormal\"><span class=\"f_KidzNormal\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormal\"><span class=\"f_KidzNormal\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r"
})
