hmLoadTopic({
hmKeywords:"",
hmTitle:"Decline a proposal",
hmDescription:"Tip Many proposals will be declined without going through any meeting or consideration procedure. This is standard practice and there may be a number of valid reasons for doing",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"devmanfunction.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > Workflow",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Decline a proposal<\/span><\/p>\n\r",
hmBody:"<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 2.3750rem 0 2.3750rem;\"><table style=\"border:none;border-spacing:0;padding:0;line-height: 1.38;\"><tr style=\"vertical-align:baseline\"><td style=\"border:none;padding:0;width:1.1250rem\"><img id=\"TOGGLE0186A1_ICON\" class=\"dropdown-toggle-icon\" alt=\"Some suggestion when adding a new proposal\" title=\"Some suggestion when adding a new proposal\" style=\"margin:0;width:0.5625rem;height:0.5625rem;border:none\" src=\".\/images\/hmtoggle_arrow0.gif\"\/><\/td><td style=\"border:none;padding:0\"><span class=\"f_KidzNormalIndent\"><a id=\"TOGGLE0186A1_LINK\" class=\"dropdown-toggle\" title=\"Some suggestion when adding a new proposal\" href=\"javascript:void(0)\" data-type=\"dropdown\" data-state=\"0\" data-icon=\"TOGGLE0186A1_ICON\" data-src0=\".\/images\/hmtoggle_arrow0.gif\" data-src1=\".\/images\/hmtoggle_arrow1.gif\">Tip<\/a><\/span><\/td><\/tr><\/table><\/div>\n\r<div id=\"TOGGLE0186A1\" class=\"dropdown-toggle-body\" style=\"text-align: left; line-height: 1.38; padding: 0 0 0 0; margin: 0 2.3750rem 0 3.5000rem;display:none\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Many proposals will be declined without going through any meeting or consideration procedure.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">This is standard practice and there may be a number of valid reasons for doing so.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Applicants may want to know the reason why their proposal has been declined.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">It is therefore good practice to record all proposals and the reason why it hasn\'t been accepted. <\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">You may receive another application in the future and having on record the comments from an earlier proposal is vital.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r"
})
