hmLoadTopic({
hmKeywords:"",
hmTitle:"DevMan components",
hmDescription:"Overview  DevMan includes in one comprehensive application  the following  components  usually only found in separate applications. Integrated with your contacts i.e. the organi",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"devmanfunction.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > Workflow",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">DevMan components<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzHeader12\"><span class=\"f_KidzHeader12\">Overview<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">DevMan includes in one comprehensive application &nbsp;the following &nbsp;components &nbsp;usually only found in separate applications.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Integrated with your <a href=\"javascript:void(0);\" data-target=\"gsycontact.js\" class=\"popuplink\">contacts<\/a> i.e. the <a href=\"javascript:void(0);\" data-target=\"gsyorganisation.js\" class=\"popuplink\">organisations<\/a>, <a href=\"javascript:void(0);\" data-target=\"gsyperson.js\" class=\"popuplink\">persons<\/a>, <a href=\"javascript:void(0);\" data-target=\"gsyproposalproject.js\" class=\"popuplink\">proposals<\/a> (project), bursaries and the <a href=\"javascript:void(0);\" data-target=\"gsyinteraction.js\" class=\"popuplink\">interactions<\/a> with them.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_KidzNormalIndent\"><a href=\"batchupdate.html\" class=\"topiclink\">Batch update<\/a><\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_KidzNormalIndent\"><a href=\"grantmanagement.html\" class=\"topiclink\">Grantmaking<\/a><\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_KidzNormalIndent\"><a href=\"bursarymanagement.html\" class=\"topiclink\">Bursary management<\/a><\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r"
})
