hmLoadTopic({
hmKeywords:"Email,Email Send",
hmTitle:"Send an email",
hmDescription:"There are a number of places in the program from where you can conveniently send an email to someone or a group of persons.",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"user.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > User settings > Personal preferences",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Send an email<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">There are a number of places in the program from where you can conveniently send an email to someone or a group of persons.<\/span><br \/>\n\r<span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">1.<\/span><span class=\"f_KidzNormalIndent\">If needed first search for the contact (make sure your contact has an email address), tick your selection and click Send and choose Email.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">2.<\/span><span class=\"f_KidzNormalIndent\">Enter the details such as the &quot;From&quot; address and &quot;Subject&quot; line. &nbsp;<\/span><br \/>\n\r<span class=\"f_KidzNormalIndent\">You can type your message directly into the block or you may choose a template (see Mailshot templates.)<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">3.<\/span><span class=\"f_KidzNormalIndent\">Once you\'re satisfied with your email and the address is valid click Send.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">4.<\/span><span class=\"f_KidzNormalIndent\">Go to the View log to check status of items sent. &nbsp;If you wish to send an email to a group of people see create a mailshot.<\/span><\/p>"
})
