hmLoadTopic({
hmKeywords:"Contact,Contact Person, add,Person,Person Add",
hmTitle:"Alter primary contact",
hmDescription:"Search for and select the proposal \/ project and change to \"edit\" mode.",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"devmanfunction.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > Workflow",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Alter primary contact<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">1.<\/span><span class=\"f_KidzNormalIndent\"><a href=\"searchlookup.html\" class=\"topiclink\">Search<\/a> for and select the proposal \/ project and change to &quot;edit&quot; mode.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Highlight and clear the existing name and enter the name of the new contact. Make any other changes and &quot;save and close&quot;.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 2.3750rem 0 2.3750rem;\"><table style=\"border:none;border-spacing:0;padding:0;line-height: 1.38;\"><tr style=\"vertical-align:baseline\"><td style=\"border:none;padding:0;width:1.1250rem\"><img id=\"TOGGLE0186A1_ICON\" class=\"dropdown-toggle-icon\" alt=\"hmtoggle_arrow0\" style=\"margin:0;width:0.5625rem;height:0.5625rem;border:none\" src=\".\/images\/hmtoggle_arrow0.gif\"\/><\/td><td style=\"border:none;padding:0\"><span class=\"f_KidzNormalIndent\"><a id=\"TOGGLE0186A1_LINK\" class=\"dropdown-toggle\" href=\"javascript:void(0)\" data-type=\"dropdown\" data-state=\"0\" data-icon=\"TOGGLE0186A1_ICON\" data-src0=\".\/images\/hmtoggle_arrow0.gif\" data-src1=\".\/images\/hmtoggle_arrow1.gif\">Change the primary contact<\/a><\/span><\/td><\/tr><\/table><\/div>\n\r<div id=\"TOGGLE0186A1\" class=\"dropdown-toggle-body\" style=\"text-align: left; text-indent: 0; line-height: 1.38; padding: 0 0 0 0; margin: 0 2.3750rem 0 2.3750rem;display:none\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Normal\"><img alt=\"ContactChange\" style=\"margin:0;width:47.1875rem;height:18.4375rem;border:none\" src=\".\/images\/contactchange.png\"\/><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r"
})
