hmLoadTopic({
hmKeywords:"",
hmTitle:"Contacts",
hmDescription:"How do I create an employee \/ employer link? A link is automatically established between an employer and an employee when you choose the organisation a person belongs to.",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"devmanfunction.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > Workflow",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Contacts<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 2.3750rem 0 2.3750rem;\"><table style=\"border:none;border-spacing:0;padding:0;line-height: 1.38;\"><tr style=\"vertical-align:baseline\"><td style=\"border:none;padding:0;width:1.1250rem\"><span class=\"f_KidzNormalIndent\">  <img id=\"toggle0186a1_ICON\" class=\"dropdown-toggle-icon\" alt=\"hmtoggle_plus0\" style=\"margin:0;width:0.5625rem;height:0.5625rem;border:none\" src=\".\/images\/hmtoggle_plus0.gif\"\/><\/span><\/td><td style=\"border:none;padding:0\"><span class=\"f_KidzNormalIndent\"><a id=\"toggle0186a1_LINK\" class=\"dropdown-toggle\" href=\"javascript:void(0)\" data-type=\"dropdown\" data-state=\"0\" data-icon=\"toggle0186a1_ICON\" data-src0=\".\/images\/hmtoggle_plus0.gif\" data-src1=\".\/images\/hmtoggle_plus1.gif\">How do I create an employee \/ employer link?<\/a><\/span><\/td><\/tr><\/table><\/div>\n\r<div id=\"toggle0186a1\" class=\"dropdown-toggle-body\" style=\"text-align: left; text-indent: 0; line-height: 1.38; padding: 0 0 0 0; margin: 0 2.3750rem 0 2.3750rem;display:none\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">A link is automatically established between an employer and an employee when you choose the organisation a person belongs to.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">The steps for creating a link manually, see <a href=\"linking.html#projectlink\" class=\"topiclink\">Create a link<\/a>. &nbsp;Instead of searching for a project, search for a person (employee), and Add &gt; Link &gt; Organisation (employer) link.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r"
})
