hmLoadTopic({
hmKeywords:"",
hmTitle:"Reports",
hmDescription:"How do I print a report that includes a graph? A graph can only be displayed on a report that features statistical information.  See Printing project reports and Statistical pr",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"user.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > User settings > Personal preferences",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Reports<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><img id=\"TOGGLE0186A1_ICON\" class=\"dropdown-toggle-icon\" alt=\"hmtoggle_plus0\" style=\"margin:0;width:0.5625rem;height:0.5625rem;border:none\" src=\".\/images\/hmtoggle_plus0.gif\"\/> &nbsp; &nbsp; &nbsp; &nbsp;<span class=\"f_KidzNormalIndent\"><a id=\"TOGGLE0186A1_LINK\" class=\"dropdown-toggle\" href=\"javascript:void(0)\" data-type=\"dropdown\" data-state=\"0\" data-icon=\"TOGGLE0186A1_ICON\" data-src0=\".\/images\/hmtoggle_plus0.gif\" data-src1=\".\/images\/hmtoggle_plus1.gif\">How do I print a report that includes a graph?<\/a><\/span><\/p>\n\r<div id=\"TOGGLE0186A1\" class=\"dropdown-toggle-body\" style=\"text-align: left; text-indent: 0; line-height: 1.38; padding: 0 0 0 0; margin: 0 2.3750rem 0 2.3750rem;display:none\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">A graph can only be displayed on a report that features statistical information. &nbsp;See <a href=\"rptproject.html\" class=\"topiclink\">Printing project reports<\/a> and <a href=\"rptprojectstats.html\" class=\"topiclink\">Statistical project reports<\/a>.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><img id=\"TOGGLE0186A2_ICON\" class=\"dropdown-toggle-icon\" alt=\"hmtoggle_plus0\" style=\"margin:0;width:0.5625rem;height:0.5625rem;border:none\" src=\".\/images\/hmtoggle_plus0.gif\"\/> &nbsp; &nbsp; &nbsp; &nbsp;<span class=\"f_KidzNormalIndent\"><a id=\"TOGGLE0186A2_LINK\" class=\"dropdown-toggle\" href=\"javascript:void(0)\" data-type=\"dropdown\" data-state=\"0\" data-icon=\"TOGGLE0186A2_ICON\" data-src0=\".\/images\/hmtoggle_plus0.gif\" data-src1=\".\/images\/hmtoggle_plus1.gif\">How do I export a report to Excel?<\/a><\/span><\/p>\n\r<div id=\"TOGGLE0186A2\" class=\"dropdown-toggle-body\" style=\"text-align: left; text-indent: 0; line-height: 1.38; padding: 0 0 0 0; margin: 0 2.3750rem 0 2.3750rem;display:none\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Choose to Microsoft Excel in the Print preview menu. For more information see Print media.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r"
})
