hmLoadTopic({
hmKeywords:"Approach,Approach Add",
hmTitle:"Add an approach",
hmDescription:"Before adding an approach to a project ensure that the details of the Organisation or Person that you are approaching are on the system.  If not, add an organisation or add a...",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"user.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > User settings > Personal preferences",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Add an approach<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Before adding an approach to a project ensure that the details of the Organisation or Person that you are approaching are on the system. &nbsp;If not, <a href=\"organisations.html#organisationadd\" class=\"topiclink\">add an organisation<\/a> or <a href=\"people.html#personadd\" class=\"topiclink\">add a person<\/a>. <\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">1.<\/span><span class=\"f_KidzNormalIndent\">You can add an approach <\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">2.<\/span><span class=\"f_KidzNormalIndent\">Search for and select the project you are seeking funds for. &nbsp;Go to Add &gt; Approach.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">3.<\/span><span class=\"f_KidzNormalIndent\">Once you have captured all the necessary information, Save &gt; Save and close. &nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">4.<\/span><span class=\"f_KidzNormalIndent\">As you make contact from the prospect approached, you can <a href=\"fdrapproachchangestatus.html\" class=\"topiclink\">change the approach status<\/a>.<\/span><\/p>"
})
