hmLoadTopic({
hmKeywords:"",
hmTitle:"Managing financials",
hmDescription:"The management of financials is a core component of both Grantmaking and Fundraising.",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"devmanfunction.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > Workflow",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Managing financials<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">The management of financials is a core component of both Grantmaking and Fundraising.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Whether you are doing grant-making or fundraising DevMan can transfer financials to your GL accounting system. <\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Data between the two systems is this in synch. Cuts down on work and helps to reduce errors associated with double entry.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><br \/>\n\r<span class=\"f_KidzNormalIndent\" style=\"font-weight: bold;\">Grantmaking<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Amounts requested in the proposals received, recommendations made and approved and tranches paid. In some cases the grants may be an in-kind donation (training or other expertise or physical goods) rather than money. Devman no longer requires that a monetary value be given to in-kind donations. <\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Provision is made for you to record these against your own grantmaking budget (macro-budget). Once a project is approved you can allocate the funds by adding a pledge, and once the payment has been made, pay the pledge or add a payment.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\" style=\"font-weight: bold;\">Fundraising<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Amounts requested in the proposals received, recommendations made and approved and tranches paid. In some cases the grants may be an in-kind donation rather than money. Devman does not requires that a monetary value be given to these in-kind donations. <\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Provision is made for you to record these against your own grantmaking budget (macro-budget). Once a project is approved you can allocate the funds by adding a pledge, and once the payment has been made, pay the pledge or add a payment.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r"
})
