hmLoadTopic({
hmKeywords:"",
hmTitle:"Internet Explorer Script Errors",
hmDescription:"A Web page may not display or work correctly, and you may receive either a warning icon or a error message similar to what you see here. ",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"user.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > User settings > Personal preferences",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Internet Explorer Script Errors<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">A Web page may not display or work correctly, and you may receive either a warning icon or a error message similar to what you see here. <\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">You can display this message by double-clicking the warning icon displayed in the Status Bar.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Click <a href=\"iescripterrorfix.html\" class=\"topiclink\">here<\/a> to see what can be done to prevent this from happening.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent2\"><img alt=\"IEWarningIcon\" style=\"margin:0;width:9.2500rem;height:7.8750rem;border:none\" src=\".\/images\/iewarningicon.png\"\/><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 2.3750rem 0 2.3750rem;\"><table style=\"border:none;border-spacing:0;padding:0;line-height: 1.38;\"><tr style=\"vertical-align:baseline\"><td style=\"border:none;padding:0;width:1.1250rem\"><img id=\"toggle0186a1_ICON\" class=\"dropdown-toggle-icon\" alt=\"hmtoggle_plus0\" style=\"margin:0;width:0.5625rem;height:0.5625rem;border:none\" src=\".\/images\/hmtoggle_plus0.gif\"\/><\/td><td style=\"border:none;padding:0\"><span class=\"f_KidzNormalIndent\"><a id=\"toggle0186a1_LINK\" class=\"dropdown-toggle\" href=\"javascript:void(0)\" data-type=\"dropdown\" data-state=\"0\" data-icon=\"toggle0186a1_ICON\" data-src0=\".\/images\/hmtoggle_plus0.gif\" data-src1=\".\/images\/hmtoggle_plus1.gif\">If you click Show Details, error details that resemble the following may appear:<\/a><\/span><\/td><\/tr><\/table><\/div>\n\r<div id=\"toggle0186a1\" class=\"dropdown-toggle-body\" style=\"text-align: left; line-height: 1.38; padding: 0 0 0 0; margin: 0 2.3750rem 0 3.5000rem;display:none\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_KidzNormalIndent\"><img alt=\"IEWarningMessage\" style=\"margin:0;width:45.4375rem;height:26.0625rem;border:none\" src=\".\/images\/iewarningmessage.png\"\/><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: -1.1250rem; margin: 0 2.3750rem 0 3.5000rem;\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r"
})
