hmLoadTopic({
hmKeywords:"Budget",
hmTitle:"Budgets",
hmDescription:"Macro Budgets  It is important to load your budgets before capturing any pledges or payments.  Some budgets are relatively simple, with one lump sum that is available to spend",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"devmanfunction.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > Workflow",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Budgets<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Macro Budgets<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">It is important to load your <a href=\"javascript:void(0);\" data-target=\"gsybudget.js\" class=\"popuplink\">budgets<\/a> before capturing any pledges or payments.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Some budgets are relatively simple, with one lump sum that is available to spend over a certain period of time. &nbsp;Other budgets are very complex, and may be broken down into different departments, regions or focus areas. &nbsp;You can load the budget of more than one organisation and up to three budget descriptions (levels) on the system.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">To set up a budget on Development Manager is a fairly complex task, and you may need to contact the Kidz Africa Team to help you enter your budget. <\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">You can <a href=\"rvnbudgetview.html\" class=\"topiclink\">view a budget<\/a>, enabling you to assess how much has been pledged, how much has been paid, and what funds are still available to be disbursed. You can also <a href=\"rvnbudgetreport.html\" class=\"topiclink\">print a budget report<\/a>.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><a id=\"microbudgets\" class=\"hmanchor\"><\/a><span class=\"f_KidzNormalIndent\">Micro Budgets (project budgets)<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Often when funds are allocated to a project, the full amount is broken down into various budget items. &nbsp;For example, part of the money for a project may be allocated to administration, transport and printing costs. &nbsp;If you would like to record this information about your project, you need to have the option enabled on your system, so please contact us.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">Once your budget categories have been set up on Development Manager for you, you can create your project budget, edit it and print reports.<\/span><\/p>\n\r"
})
