hmLoadTopic({
hmKeywords:"Password,Password Change",
hmTitle:"Change password",
hmDescription:"Change my password Select Home > My settings > Change password.   Enter your existing password, and then enter your new password and confirm it. Then select Save and close.",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"devmancomponent.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > Reference > DevMan components > Batch update",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Change password<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzNormalIndent\"><img id=\"TOGGLE0186A1_ICON\" class=\"dropdown-toggle-icon\" alt=\"Change password\" title=\"Change password\" style=\"margin:0;width:0.5625rem;height:0.5625rem;border:none\" src=\".\/images\/hmtoggle_arrow0.gif\"\/> &nbsp; &nbsp; &nbsp; &nbsp;<span class=\"f_KidzNormalIndent\"><a id=\"TOGGLE0186A1_LINK\" class=\"dropdown-toggle\" title=\"Change password\" href=\"javascript:void(0)\" data-type=\"dropdown\" data-state=\"0\" data-icon=\"TOGGLE0186A1_ICON\" data-src0=\".\/images\/hmtoggle_arrow0.gif\" data-src1=\".\/images\/hmtoggle_arrow1.gif\">Change my password<\/a><\/span><\/p>\n\r<div id=\"TOGGLE0186A1\" class=\"dropdown-toggle-body\" style=\"text-align: left; text-indent: 0; line-height: 1.38; padding: 0 0 0 0; margin: 0 2.3750rem 0 2.3750rem;display:none\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">1.<\/span><span class=\"f_KidzNormalIndent\">Select <\/span><span class=\"f_KidzNormalIndent\" style=\"font-style: italic; font-weight: bold;\">Home &gt; My settings &gt; Change password<\/span><span class=\"f_KidzNormalIndent\">.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><img alt=\"PreferencesPersonal\" style=\"margin:0;width:26.0625rem;height:15.3750rem;border:none\" src=\".\/images\/preferencespersonal.png\"\/><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">2.<\/span><span class=\"f_KidzNormalIndent\">Enter your existing password, and then enter your new password and confirm it. Then select <\/span><span class=\"f_KidzNormalIndent\" style=\"font-style: italic; font-weight: bold;\">Save and close<\/span><span class=\"f_KidzNormalIndent\">.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><img alt=\"PreferencesNewPassword\" style=\"margin:0;width:37.4375rem;height:10.0625rem;border:none\" src=\".\/images\/preferencesnewpassword.png\"\/><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r"
})
