hmLoadTopic({
hmKeywords:"Getting started",
hmTitle:"Settings",
hmDescription:"There are three levels in which Devman can be configured:",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"devmanfunction.html",
hmBreadCrumbs:"",
hmTitlePath:"DevMan functions > Workflow",
hmHeader:"<p class=\"p_KidzHeader1\"><span class=\"f_KidzHeader1\">Settings<\/span><\/p>\n\r",
hmBody:"<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">There are three levels in which Devman can be <a href=\"javascript:void(0);\" data-target=\"gsyconfigure.js\" class=\"popuplink\">configured<\/a>:<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">1.<\/span><span class=\"f_KidzNormalIndent\">Feature settings made in the beginning to suit your organisation \'s way of working.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">2.<\/span><span class=\"f_KidzNormalIndent\">Global or system-wide look and feel preferences and environmental settings<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">3.<\/span><span class=\"f_KidzNormalIndent\">User or personal settings and preferences that affect you only<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">4.<\/span><span class=\"f_KidzNormalIndent\">Settings and preferences for the <a href=\"newuser.html\" class=\"topiclink\">new user<\/a><\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 2.3750rem;\"><span class=\"f_KidzNormalIndent\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">5.<\/span><span class=\"f_KidzNormalIndent\">At times you may want other changes and enhancements.<\/span><br \/>\n\r<span class=\"f_KidzNormalIndent\">Should you require Devman to be <a href=\"javascript:void(0);\" data-target=\"gsycustomise.js\" class=\"popuplink\">customised<\/a> please speak to your Devman representative,<\/span><br \/>\n\r<span class=\"f_KidzNormalIndent\"> or call our support desk.<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r<p class=\"p_KidzNormalIndent\"><span class=\"f_KidzNormalIndent\">&nbsp;<\/span><\/p>\n\r"
})
