hmLoadIndex({sections:["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"],
keywords:[{kw:"18A",hrefs:["section18areceipts.html#reissue_s18"],captions:["Section 18A receipts"],subkw:[]},
{kw:"2023",hrefs:["section18areceipts.html#sars2023"],captions:["Section 18A receipts"],subkw:[]},
{kw:"Academic",hrefs:["onlineresults.html#peoplesearchadvancedacademicresults"],captions:["Online results"],subkw:[]},
{kw:"Access",hrefs:["securityadvanced.html#permissionsdevmanfunction","securityadvanced.html#permissionsuseraccess"],captions:["Advanced","Advanced"],subkw:[]},
{kw:"Add",hrefs:["devsecurity.html#userprofile"],captions:["Security"],subkw:[]},
{kw:"Address",hrefs:["email.html#failedaddressvalidate"],captions:["Email"],subkw:[]},
{kw:"Advanced",hrefs:["onlineresults.html#peoplesearchadvancedacademicresults","searching.html#searchadvanced"],captions:["Online results","Searching"],subkw:[]},
{kw:"application",hrefs:["onlineapplications.html#reopenapplication"],captions:["Online applications"],subkw:[]},
{kw:"applications",hrefs:["onlineapplications.html#reportingissues"],captions:["Online applications"],subkw:[]},
{kw:"applicatoin",hrefs:["onlineapplications.html#resendfailedemail"],captions:["Online applications"],subkw:[]},
{kw:"Attach",hrefs:["documentmanagement.html#documentupload"],captions:["Document management"],subkw:[]},
{kw:"Attachment",hrefs:["documentmanagement.html","dossier.html"],captions:["Document management","Dossier"],subkw:[]},
{kw:"Beneficiaries",hrefs:[],captions:[],subkw:[{kw:"Add",hrefs:["prjbeneficiariesadd.html"],captions:["Add beneficiary"],subkw:[]}]},
{kw:"Bookmarks",hrefs:["navigation.html#favouritesmanage"],captions:["Navigation"],subkw:[]},
{kw:"browser",hrefs:["faqgeneral.html#browser"],captions:["General"],subkw:[]},
{kw:"Budget",hrefs:["rvnbudget.html"],captions:["Budgets"],subkw:[{kw:"Print",hrefs:["rvnbudgetreport.html"],captions:["Print a budget report"],subkw:[]},
{kw:"View",hrefs:["rvnbudgetview.html"],captions:["View a budget"],subkw:[]}]},
{kw:"Certificate",hrefs:["section18areceipts.html#sars2023","section18areceipts.html#selfserviceupdate"],captions:["Section 18A receipts","Section 18A receipts"],subkw:[]},
{kw:"change",hrefs:["faqgeneral.html#changepassword"],captions:["General"],subkw:[]},
{kw:"Clicks",hrefs:["email.html#linktrack"],captions:["Email"],subkw:[]},
{kw:"Contact",hrefs:[],captions:[],subkw:[{kw:"Organisation, add",hrefs:["prjprojectsummary.html"],captions:["Project summary"],subkw:[]},
{kw:"Person, add",hrefs:["entpersoncontactalter.html"],captions:["Alter primary contact"],subkw:[]},
{kw:"Search",hrefs:["entsearchadv.html"],captions:["Advanced search"],subkw:[]}]},
{kw:"Contacts",hrefs:[],captions:[],subkw:[{kw:"Linking",hrefs:["entlink.html"],captions:["Linking Contacts"],subkw:[]}]},
{kw:"Count",hrefs:["email.html#linktrack"],captions:["Email"],subkw:[]},
{kw:"Data",hrefs:["devsecurity.html#faqsecurityanchor","devsecurity.html#faqdatasecure"],captions:["Security","Security"],subkw:[]},
{kw:"Details",hrefs:["section18areceipts.html#selfserviceupdate"],captions:["Section 18A receipts"],subkw:[]},
{kw:"DevMan functions",hrefs:["securityadvanced.html#permissionsdevmanfunction"],captions:["Advanced"],subkw:[]},
{kw:"Document",hrefs:["email.html#documentlink","documentmanagement.html","documentmanagement.html#documentupload"],captions:["Email","Document management","Document management"],subkw:[]},
{kw:"Donation",hrefs:[],captions:[],subkw:[{kw:"Add",hrefs:["rvndonation.html"],captions:["Donation"],subkw:[]}]},
{kw:"Donor",hrefs:["section18areceipts.html#sars2023"],captions:["Section 18A receipts"],subkw:[]},
{kw:"Dossier",hrefs:["documentmanagement.html","dossier.html"],captions:["Document management","Dossier"],subkw:[{kw:"Viewing",hrefs:["entdossierview.html"],captions:["View dossier"],subkw:[]}]},
{kw:"email",hrefs:["email.html#emailsend","email.html#failedaddressvalidate","email.html#improveemaildelivery","email.html#documentlink","email.html#junkmail","onlineapplications.html#resendfailedemail"],captions:["Email","Email","Email","Email","Email","Online applications"],subkw:[{kw:"Address",hrefs:["email.html#emailaddressvalidate"],captions:["Email"],subkw:[]}]},
{kw:"Email identity",hrefs:["navigation.html#userpreferences"],captions:["Navigation"],subkw:[]},
{kw:"Email verification",hrefs:["navigation.html#userpreferences"],captions:["Navigation"],subkw:[]},
{kw:"End user requirements",hrefs:["quickguides.html#enduser"],captions:["Product guides"],subkw:[]},
{kw:"Envelopes",hrefs:[],captions:[],subkw:[{kw:"Print",hrefs:["rptcontactenvelope.html"],captions:["Envelope printing"],subkw:[]}]},
{kw:"Events",hrefs:["eventmanagement.html#eventmodulefeatures","searching.html#searchoptions","searching.html#searchadvanced"],captions:["Event management","Searching","Searching"],subkw:[]},
{kw:"excel",hrefs:["importsandupdates.html#importer"],captions:["Imports and updates"],subkw:[]},
{kw:"explorer",hrefs:["faqgeneral.html#browser"],captions:["General"],subkw:[]},
{kw:"Export",hrefs:[],captions:[],subkw:[{kw:"Reports",hrefs:["rptcontactexport.html"],captions:["Exporting reports"],subkw:[]}]},
{kw:"failed",hrefs:["onlineapplications.html#resendfailedemail"],captions:["Online applications"],subkw:[]},
{kw:"FAQ",hrefs:["navigation.html#faqnavigation","textmessage.html#smsfaq"],captions:["Navigation","SMS"],subkw:[]},
{kw:"Favourites",hrefs:["navigation.html#favouritesmanage"],captions:["Navigation"],subkw:[]},
{kw:"FAYT",hrefs:["searching.html#sayt"],captions:["Searching"],subkw:[]},
{kw:"Fields",hrefs:["section18areceipts.html#sars2023"],captions:["Section 18A receipts"],subkw:[]},
{kw:"filter sort resize",hrefs:["navigation.html#gridfeature"],captions:["Navigation"],subkw:[]},
{kw:"Find",hrefs:["searching.html#sayt"],captions:["Searching"],subkw:[]},
{kw:"Getting started",hrefs:["setting.html"],captions:["Settings"],subkw:[]},
{kw:"Giving",hrefs:["onlinegiving.html#onlinegivingprojects"],captions:["Online giving"],subkw:[]},
{kw:"Grid",hrefs:["onlineresults.html#peoplesearchadvancedacademicresults"],captions:["Online results"],subkw:[]},
{kw:"Grids",hrefs:[],captions:[],subkw:[{kw:"Font, default",hrefs:["personalpreference.html"],captions:["Personal preferences"],subkw:[]},
{kw:"Row, number displayed",hrefs:["personalpreference.html"],captions:["Personal preferences"],subkw:[]}]},
{kw:"Guide",hrefs:["devsecurity.html#faqpopia"],captions:["Security"],subkw:[]},
{kw:"Guides",hrefs:["quickguides.html#enduser"],captions:["Product guides"],subkw:[]},
{kw:"import",hrefs:["importsandupdates.html#importer"],captions:["Imports and updates"],subkw:[]},
{kw:"Important",hrefs:["onlineresults.html#notes"],captions:["Online results"],subkw:[]},
{kw:"Interaction",hrefs:[],captions:[],subkw:[{kw:"Add",hrefs:["actinteractionadd.html"],captions:["Add an interaction"],subkw:[]},
{kw:"New",hrefs:["actinteractionadd.html"],captions:["Add an interaction"],subkw:[]},
{kw:"View",hrefs:["actinteractionview.html"],captions:["View a past interaction"],subkw:[]}]},
{kw:"internet",hrefs:["faqgeneral.html#browser"],captions:["General"],subkw:[]},
{kw:"Issue",hrefs:["faqsupport.html#helpandsupport","faqsupport.html#reportissue"],captions:["Support","Support"],subkw:[]},
{kw:"issues",hrefs:["onlineapplications.html#reportingissues"],captions:["Online applications"],subkw:[]},
{kw:"junk",hrefs:["email.html#improveemaildelivery","email.html#junkmail"],captions:["Email","Email"],subkw:[]},
{kw:"Labels",hrefs:[],captions:[],subkw:[{kw:"Print",hrefs:["rptcontactlabel.html"],captions:["Label printing"],subkw:[]}]},
{kw:"Letter",hrefs:["faqletter.html"],captions:["Letters and templates"],subkw:[]},
{kw:"Link",hrefs:["email.html#documentlink","entlink.html"],captions:["Email","Linking Contacts"],subkw:[{kw:"Employee",hrefs:["entlink.html"],captions:["Linking Contacts"],subkw:[]},
{kw:"Employer",hrefs:["entlink.html"],captions:["Linking Contacts"],subkw:[]},
{kw:"Organisation",hrefs:["entlink.html"],captions:["Linking Contacts"],subkw:[]},
{kw:"Person",hrefs:["entlink.html"],captions:["Linking Contacts"],subkw:[]}]},
{kw:"Linking",hrefs:["entlink.html"],captions:["Linking Contacts"],subkw:[]},
{kw:"Links",hrefs:["email.html#linktrack"],captions:["Email"],subkw:[]},
{kw:"List",hrefs:["onlinegiving.html#onlinegivingprojects"],captions:["Online giving"],subkw:[]},
{kw:"mail",hrefs:["email.html#junkmail"],captions:["Email"],subkw:[]},
{kw:"Mailshot",hrefs:["mailshot.html#mailshotrecipients","mailshot.html#schedulemailshot"],captions:["Mailshot","Mailshot"],subkw:[]},
{kw:"Mailshots",hrefs:["searching.html#searchoptions","searching.html#searchadvanced"],captions:["Searching","Searching"],subkw:[]},
{kw:"Managed by",hrefs:["eventmanagement.html#eventmodulefeatures"],captions:["Event management"],subkw:[]},
{kw:"Navigation",hrefs:["navigation.html#faqnavigation"],captions:["Navigation"],subkw:[]},
{kw:"Notes",hrefs:["onlineresults.html#notes"],captions:["Online results"],subkw:[]},
{kw:"notifications",hrefs:["email.html#junkmail"],captions:["Email"],subkw:[]},
{kw:"online",hrefs:["onlinegiving.html#onlinegivingprojects","onlineapplications.html#reportingissues","onlineapplications.html#reopenapplication","onlineapplications.html#resendfailedemail"],captions:["Online giving","Online applications","Online applications","Online applications"],subkw:[]},
{kw:"Organisation",hrefs:[],captions:[],subkw:[{kw:"Add",hrefs:["prjprojectsummary.html"],captions:["Project summary"],subkw:[]}]},
{kw:"Password",hrefs:["faqgeneral.html#changepassword"],captions:["General"],subkw:[{kw:"Change",hrefs:["setpasswordchange.html"],captions:["Change password"],subkw:[]}]},
{kw:"Payment",hrefs:[],captions:[],subkw:[{kw:"Pledge (payment made)",hrefs:["rvnpaymentpledgepay.html"],captions:["Pay a pledge"],subkw:[]},
{kw:"Pledge (payment received)",hrefs:["rvnpaymentadd.html"],captions:["Add a payment"],subkw:[]}]},
{kw:"people",hrefs:["onlineresults.html#peoplesearchadvancedacademicresults","searching.html#searchoptions"],captions:["Online results","Searching"],subkw:[]},
{kw:"Permissions",hrefs:["securityadvanced.html#permissionsdevmanfunction","securityadvanced.html#permissionsuseraccess","devadministrationmine.html#userrights"],captions:["Advanced","Advanced","Security"],subkw:[]},
{kw:"Person",hrefs:[],captions:[],subkw:[{kw:"Add",hrefs:["entpersoncontactalter.html"],captions:["Alter primary contact"],subkw:[]}]},
{kw:"Personal",hrefs:["navigation.html#userpreferences"],captions:["Navigation"],subkw:[]},
{kw:"Pledge",hrefs:[],captions:[],subkw:[{kw:"Add (Payment made)",hrefs:["rvnpaymentpledgeadd.html"],captions:["Add a pledge"],subkw:[]},
{kw:"Donation",hrefs:["committedgiving.html","rvndonationpledgeadd.html","rvnpledge.html"],captions:["Commitment - giving","Add a pledge","Pledge"],subkw:[]},
{kw:"Pay",hrefs:["rvnpaymentadd.html","rvnpaymentpledgepay.html"],captions:["Add a payment","Pay a pledge"],subkw:[]},
{kw:"Pay donation",hrefs:["rvndonationpledgepay.html"],captions:["Pay a pledge"],subkw:[]}]},
{kw:"POPIA",hrefs:["devsecurity.html#faqpopia"],captions:["Security"],subkw:[]},
{kw:"Popup",hrefs:[],captions:[],subkw:[{kw:"Blockers",hrefs:["faqpopups.html"],captions:["Popup blockers"],subkw:[]},
{kw:"Not displaying",hrefs:["faqpopups.html"],captions:["Popup blockers"],subkw:[]},
{kw:"Remove popup blocker alerts",hrefs:["faqpopups.html"],captions:["Popup blockers"],subkw:[]}]},
{kw:"Preferences",hrefs:["navigation.html#userpreferences","personalpreference.html"],captions:["Navigation","Personal preferences"],subkw:[]},
{kw:"Print",hrefs:["faqprintingproblems.html"],captions:["Printing & printing problems"],subkw:[{kw:"HTML",hrefs:["printmedia.html"],captions:["Print media"],subkw:[]},
{kw:"PDF",hrefs:["printmedia.html"],captions:["Print media"],subkw:[]},
{kw:"Word",hrefs:["printmedia.html"],captions:["Print media"],subkw:[]}]},
{kw:"Privilege",hrefs:["securityadvanced.html#permissionsuseraccess"],captions:["Advanced"],subkw:[]},
{kw:"Profile",hrefs:["devsecurity.html#userprofile"],captions:["Security"],subkw:[]},
{kw:"Project",hrefs:["onlinegiving.html#onlinegivingprojects"],captions:["Online giving"],subkw:[{kw:"Beneficiaries",hrefs:["prjbeneficiaries.html","prjbeneficiariesadd.html"],captions:["Project beneficiaries","Add beneficiary"],subkw:[]},
{kw:"Partners",hrefs:["entlink.html"],captions:["Linking Contacts"],subkw:[]},
{kw:"Tutorial",hrefs:["proposal.html"],captions:["Working with projects and proposals"],subkw:[]}]},
{kw:"Proposal",hrefs:[],captions:[],subkw:[{kw:"Tutorial",hrefs:["proposal.html"],captions:["Working with projects and proposals"],subkw:[]}]},
{kw:"recipient",hrefs:["mailshot.html#mailshotrecipients"],captions:["Mailshot"],subkw:[]},
{kw:"reissue",hrefs:["section18areceipts.html#reissue_s18"],captions:["Section 18A receipts"],subkw:[]},
{kw:"Relationships",hrefs:["entlink.html"],captions:["Linking Contacts"],subkw:[]},
{kw:"Re-open",hrefs:["onlineapplications.html#reopenapplication"],captions:["Online applications"],subkw:[]},
{kw:"Report",hrefs:["faqsupport.html#helpandsupport","faqsupport.html#reportissue"],captions:["Support","Support"],subkw:[]},
{kw:"reporting",hrefs:["onlineapplications.html#reportingissues"],captions:["Online applications"],subkw:[]},
{kw:"Reports",hrefs:["searching.html#searchadvanced","report.html"],captions:["Searching","Report"],subkw:[{kw:"Advanced",hrefs:["importsandupdates.html","batchupdate.html"],captions:["Imports and updates","Process a batch of records"],subkw:[]},
{kw:"Budget",hrefs:["rvnbudgetreport.html"],captions:["Print a budget report"],subkw:[]},
{kw:"Contacts",hrefs:["rptcontact.html","rptcontactprofiles.html"],captions:["Printing contact reports","Printing contact profiles"],subkw:[]},
{kw:"Customisable exports",hrefs:["importsandupdates.html","batchupdate.html"],captions:["Imports and updates","Process a batch of records"],subkw:[]},
{kw:"Envelopes",hrefs:["rptcontactenvelope.html"],captions:["Envelope printing"],subkw:[]},
{kw:"Excel",hrefs:["rptcontactexport.html"],captions:["Exporting reports"],subkw:[]},
{kw:"Export",hrefs:["rptcontactexport.html"],captions:["Exporting reports"],subkw:[]},
{kw:"Labels",hrefs:["rptcontactlabel.html"],captions:["Label printing"],subkw:[]},
{kw:"Project",hrefs:["rptproject.html","rptproject_2.html"],captions:["Printing project reports","Printing finance reports"],subkw:[]},
{kw:"Project lists",hrefs:["rptprojectlists.html","rptprojectlists_2.html"],captions:["Project lists","Project lists_2"],subkw:[]},
{kw:"Report builder",hrefs:["importsandupdates.html","batchupdate.html"],captions:["Imports and updates","Process a batch of records"],subkw:[]},
{kw:"Report Layout",hrefs:["rptcontactreport.html"],captions:["Report printing"],subkw:[]},
{kw:"Statistical, project",hrefs:["rptprojectstats.html","rptprojectstats_2.html"],captions:["Statistical project reports","Statistical project reports_2"],subkw:[]}]},
{kw:"Request",hrefs:["onlineresults.html#steps"],captions:["Online results"],subkw:[]},
{kw:"Re-send",hrefs:["onlineapplications.html#resendfailedemail"],captions:["Online applications"],subkw:[]},
{kw:"Result",hrefs:["onlineresults.html#steps"],captions:["Online results"],subkw:[]},
{kw:"Results",hrefs:["onlineresults.html#peoplesearchadvancedacademicresults"],captions:["Online results"],subkw:[]},
{kw:"Rights",hrefs:["securityadvanced.html#permissionsdevmanfunction","devadministrationmine.html#userrights"],captions:["Advanced","Security"],subkw:[]},
{kw:"RSVP",hrefs:["eventmanagement.html#eventmodulefeatures"],captions:["Event management"],subkw:[]},
{kw:"SARS",hrefs:["section18areceipts.html#sars2023"],captions:["Section 18A receipts"],subkw:[]},
{kw:"Schedule",hrefs:["mailshot.html#schedulemailshot"],captions:["Mailshot"],subkw:[]},
{kw:"Scheduler",hrefs:["mailshot.html#schedulemailshot"],captions:["Mailshot"],subkw:[]},
{kw:"Search",hrefs:["onlineresults.html#peoplesearchadvancedacademicresults","searching.html#searchadvanced"],captions:["Online results","Searching"],subkw:[{kw:"Contact",hrefs:["entsearchadv.html"],captions:["Advanced search"],subkw:[]},
{kw:"Organisation",hrefs:["entsearchadv.html"],captions:["Advanced search"],subkw:[]},
{kw:"Person",hrefs:["entsearchadv.html"],captions:["Advanced search"],subkw:[]},
{kw:"Project",hrefs:["entsearchadv.html"],captions:["Advanced search"],subkw:[]}]},
{kw:"Search as you type",hrefs:["searching.html#sayt"],captions:["Searching"],subkw:[]},
{kw:"section",hrefs:["section18areceipts.html#reissue_s18"],captions:["Section 18A receipts"],subkw:[]},
{kw:"Secure",hrefs:["devsecurity.html#faqdatasecure"],captions:["Security"],subkw:[{kw:"Recovery",hrefs:["devsecurity.html#faqsecurityanchor"],captions:["Security"],subkw:[]}]},
{kw:"Security",hrefs:["devsecurity.html#faqpopia"],captions:["Security"],subkw:[]},
{kw:"Self",hrefs:["section18areceipts.html#selfserviceupdate"],captions:["Section 18A receipts"],subkw:[]},
{kw:"Send",hrefs:["email.html#emailsend","textmessage.html","textmessage.html#smsfaq"],captions:["Email","SMS","SMS"],subkw:[]},
{kw:"Service",hrefs:["section18areceipts.html#selfserviceupdate"],captions:["Section 18A receipts"],subkw:[]},
{kw:"Settings",hrefs:["navigation.html#userpreferences"],captions:["Navigation"],subkw:[{kw:"Personal preferences",hrefs:["personalpreference.html"],captions:["Personal preferences"],subkw:[]}]},
{kw:"SMS",hrefs:["textmessage.html","textmessage.html#smsfaq"],captions:["SMS","SMS"],subkw:[]},
{kw:"spam",hrefs:["email.html#improveemaildelivery"],captions:["Email"],subkw:[]},
{kw:"spreadsheet",hrefs:["importsandupdates.html#importer"],captions:["Imports and updates"],subkw:[]},
{kw:"Steps",hrefs:["onlineresults.html#steps"],captions:["Online results"],subkw:[]},
{kw:"Subscription",hrefs:["mailshot.html#mailshotrecipients","eventmanagement.html#eventmodulefeatures"],captions:["Mailshot","Event management"],subkw:[]},
{kw:"Support",hrefs:["faqsupport.html#helpandsupport"],captions:["Support"],subkw:[]},
{kw:"Tax",hrefs:["section18areceipts.html#sars2023","section18areceipts.html#selfserviceupdate"],captions:["Section 18A receipts","Section 18A receipts"],subkw:[]},
{kw:"Template",hrefs:[],captions:[],subkw:[{kw:"Letter",hrefs:["faqletter.html"],captions:["Letters and templates"],subkw:[]}]},
{kw:"Time",hrefs:["textmessage.html","textmessage.html#smsfaq"],captions:["SMS","SMS"],subkw:[]},
{kw:"times",hrefs:["textmessage.html"],captions:["SMS"],subkw:[]},
{kw:"Track",hrefs:["email.html#linktrack"],captions:["Email"],subkw:[]},
{kw:"Troubleshooting",hrefs:[],captions:[],subkw:[{kw:"Printing, problem",hrefs:["faqprintingproblems.html"],captions:["Printing & printing problems"],subkw:[]}]},
{kw:"Tutorial",hrefs:[],captions:[],subkw:[{kw:"Project",hrefs:["proposal.html"],captions:["Working with projects and proposals"],subkw:[]},
{kw:"Proposal",hrefs:["proposal.html"],captions:["Working with projects and proposals"],subkw:[]}]},
{kw:"Update",hrefs:["section18areceipts.html#selfserviceupdate"],captions:["Section 18A receipts"],subkw:[]},
{kw:"Upload",hrefs:["documentmanagement.html#documentupload"],captions:["Document management"],subkw:[]},
{kw:"User",hrefs:["devsecurity.html#userprofile","securityadvanced.html#permissionsuseraccess"],captions:["Security","Advanced"],subkw:[{kw:"Permissions",hrefs:["secuserpermission.html"],captions:["Set or change user permissions"],subkw:[]}]},
{kw:"Users",hrefs:["devadministrationmine.html#userrights"],captions:["Security"],subkw:[]},
{kw:"Validate",hrefs:["email.html#emailaddressvalidate","email.html#failedaddressvalidate"],captions:["Email","Email"],subkw:[]},
{kw:"Web stationery",hrefs:["eventmanagement.html#eventmodulefeatures"],captions:["Event management"],subkw:[]}]}
)
