pageinfo = [[1695125864,0,0,0,null],
	[1705420174,0,0,0,null],
	[1695125652,0,0,0,null],
	[1708584016,0,0,0,null],
	[1697625498,0,0,0,null],
	[1705063984,0,0,0,null],
	[1695125922,0,0,0,null],
	[1696325746,0,0,0,null],
	[1696325726,0,0,0,null],
	[1695125734,0,0,0,null],
	[1708063930,0,0,0,null],
	[1695125766,0,0,0,null],
	[1696325850,0,0,0,null],
	[1695125846,0,0,0,null],
	[1707746418,0,0,0,null],
	[1705502778,0,0,0,null],
	[1695125788,0,0,0,null],
	[1695125808,0,0,0,null],
	[1695125698,0,0,0,null],
	[1701861800,0,0,0,null],
	[1695125798,0,0,0,null],
	[1695125856,0,0,0,null],
	[1695125832,0,0,0,null],
	[1696325822,0,0,0,null],
	[1696325814,0,0,0,null],
	[1708609584,0,0,0,null],
	[1705670934,0,0,0,null],
	[1695125664,0,0,0,null],
	[1695125980,0,0,0,null],
	[1708427752,0,0,0,null],
	[1705670508,0,0,0,null],
	[1696325692,0,0,0,null],
	[1656505248,0,0,0,null],
	[1707818046,0,0,0,null],
	[1696325696,0,0,0,null],
	[1696325664,0,0,0,null],
	[1656505248,0,0,0,null],
	[1696325804,0,0,0,null],
	[1696325654,0,0,0,null],
	[1696325780,0,0,0,null],
	[1668146622,0,0,0,null],
	[1695125950,0,0,0,null],
	[1695125824,0,0,0,null],
	[1708426228,0,0,0,null],
	[1696325840,0,0,0,null],
	[1695125504,0,0,0,null],
	[1707818458,0,0,0,null],
	[1708600682,0,0,0,null],
	[1696405280,0,0,0,null],
	[1695125754,0,0,0,null],
	[1708583796,0,0,0,null],
	[1695125778,0,0,0,null],
	[1708608162,0,0,0,null],
	[1695125840,0,0,0,null],
	[1696325762,0,0,0,null],
	[1695125726,0,0,0,null],
	[1708426500,0,0,0,null],
	[1705067676,0,0,0,null],
	[1708063948,0,0,0,null],
	[1696325788,0,0,0,null],
	[1696325830,0,0,0,null],
	[1696325752,0,0,0,null],
	[1705067736,0,0,0,null],
	[1708513922,0,0,0,null],
	[1695125966,0,0,0,null],
	[1706525412,0,0,0,null],
	[1701855826,0,0,0,null],
	[1708064218,0,0,0,null],
	[1708593702,0,0,0,null],
	[1708597112,0,0,0,null],
	[1707491366,0,0,0,null],
	[1695125492,0,0,0,null],
	[1656505408,0,0,0,null],
	[1701861792,0,0,0,null],
	[1701855816,0,0,0,null],
	[1656505408,0,0,0,null],
	[1707743410,0,0,0,null],
	[1707726312,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1658836346,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1708515434,0,0,0,null],
	[1701854850,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1658734002,0,0,0,null],
	[1656505408,0,0,0,null],
	[1705670928,0,0,0,null],
	[1697107670,0,0,0,null],
	[1656505408,0,0,0,null],
	[1694004468,0,0,0,null],
	[1656505408,0,0,0,null],
	[1707491136,0,0,0,null],
	[1656505408,0,0,0,null],
	[1666874398,0,0,0,null],
	[1666874816,0,0,0,null],
	[1684750166,0,0,0,null],
	[1684755314,0,0,0,null],
	[1708596910,0,0,0,null],
	[1656505408,0,0,0,null],
	[1666174928,0,0,0,null],
	[1684754444,0,0,0,null],
	[1708600564,0,0,0,null],
	[1661765156,0,0,0,null],
	[1661845114,0,0,0,null],
	[1707723804,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505410,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505412,0,0,0,null],
	[1657189636,0,0,0,null],
	[1656505408,0,0,0,null],
	[1707816572,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505412,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505412,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505412,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1706271534,0,0,0,null],
	[1708513904,0,0,0,null],
	[1656505408,0,0,0,null],
	[1656505408,0,0,0,null],
	[1660835258,0,0,0,null],
	[1707484522,0,0,0,null],
	[1706524656,0,0,0,null],
	[1706519500,0,0,0,null],
	[1706521534,0,0,0,null],
	[1706525406,0,0,0,null],
	[1706261876,0,0,0,null],
	[1680530788,0,0,0,null],
	[1656505408,0,0,0,null],
	[1696325768,0,0,0,null]];
pagedata = [ ["./accountingsystemintegration.html","Accounting system integration","Overview  Reduce errors and increase productivity with a single point of entry. DevMan integrates to various finance and accounting systems, ...","./images/zoomimage.jpg"],
["./actionsdue.html","Actions due","Overview  By setting up reminders, you can keep track of which activities are due and which have been completed. Letter reminders are set up ...","./images/zoomimage.jpg"],
["./activitiesinteraction.html","Activities / Interactions","Overview  As interactions are recorded on the system, you are notified in the Weekly activity section of the Home page: You may view these ne...","./images/zoomimage.jpg"],
["./aftertheevent.html","After the event","Overview  Enhance return on investment, engage with attendees and gather feedback via post-event surveys to drive improvement.  Topics &#38;...","./images/zoomimage.jpg"],
["./attheevent.html","At the event","Overview  Build their confidence and delight your attendees with a seamless online registration experience. Manage real-time event data on th...","./images/zoomimage.jpg"],
["./beforetheevent.html","Before the event","Overview  Plan the perfect event: kick off the planning process by addressing all components of the event. Stay on schedule and create clear ...","./images/zoomimage.jpg"],
["./budget.html","Budget","Overview  Align your budgets with expenditure, use this tool to load your budget before capturing any pledges or payments. Manage and review ...","./images/zoomimage.jpg"],
["./bursary-profile.html","Bursary profile","Overview  Initiate and solidify connections between students, sponsors and institutions. Provide comprehensive insight on key bursary data. &#38;...","./images/zoomimage.jpg"],
["./bursarymanagement.html","Bursary management","Overview  Transform your bursary management process with configurable, versatile workflow designed to streamline your tasks. Use the DevMan b...","./images/zoomimage.jpg"],
["./businessunits.html","Business units","Overview  DevMan allows you to set up all your business units for an organisation in an easy to see hierarchy using 4 levels. Your institutio...","./images/zoomimage.jpg"],
["./commitmentsbudget.html","Commitments","Overview    Topics","./images/zoomimage.jpg"],
["./consent.html","Consent","Overview  Get your POPIA implementation plan off the ground, and painlessly achieve compliance by making practical use of the Consent module....","./images/zoomimage.jpg"],
["./contract.html","Contracts","Overview  Use this feature to manage all your contracts.  Upload, store and organise your agreement records for easy access and retrieva...","./images/zoomimage.jpg"],
["./debitorders.html","Debit orders","Overview  Drive efficiency, streamline the monthly administration of your debit order donors by using DevMan’s integration features.  To...","./images/zoomimage.jpg"],
["./devcommunication.html","Communication","Overview  Engage and build rapport with your audience via email and SMS channels. Take advantage of workflow automation to expand communicati...","./images/zoomimage.jpg"],
["./devcontact.html","Contacts","Overview  Use this feature to manage all your contacts.  These may be linked to other contacts, organisations or projects.  Topics ...","./images/zoomimage.jpg"],
["./devdashboard.html","Dashboards","Overview  Transform data sets into analytical snapshots. View crucial information at a glance. Dashboards are accessible on the Home page, &#38;n...","./images/zoomimage.jpg"],
["./devfinance.html","Finance","Overview  DevMan’s financial management component, designed to complement or integrate to your accounting systems is crucial for effective ma...","./images/zoomimage.jpg"],
["./devmanfunction.html","DevMan functions","Working procedures","./images/zoomimage.jpg"],
["./devsecurity.html","Security","Overview  Computer security is an important component of a successful organisation. Avoid complacency, control access to activities and data ...","./images/zoomimage.jpg"],
["./documentmanagement.html","Document management","Overview  Reduce paper, and increase efficiency with the DevMan dossier (document) upload feature.  Topics  Features Upload documen...","./images/zoomimage.jpg"],
["./donationdepositprocess.html","Donation deposit process","Overview  Streamline the monthly administration and allocation of your donations received via direct bank deposit.  Topics  How it ...","./images/zoomimage.jpg"],
["./donations.html","Donations","Overview  Capture donations directly and if required, send a thank you letter to the donor.   Topics  Features Link donations to th...","./images/zoomimage.jpg"],
["./donorengagement.html","Donor engagement","Overview  Nurture relationships with donors to improve engagement and monitor the various prospect stages. Evaluate metrics by tracking inter...","./images/zoomimage.jpg"],
["./donorprofile.html","Donor profile","Overview  The starting point in your cultivation of lifelong relationships with both organisations and individuals. Empower your team with ac...","./images/zoomimage.jpg"],
["./email.html","Email","Overview  Ensure your email campaigns are targeted and relevant, providing value to recipients to maintain their trust and engagement.  ...","./images/zoomimage.jpg"],
["./emailsetup.html","Email setup","Overview  Verify your email address and learn how to configure your sending domain.  Topics  Set up email The email address you wis...","./images/zoomimage.jpg"],
["./eventmanagement.html","Event management","Overview  Create and manage memorable events, connect and engage with attendees to provide a more personalised experience. Use this module to...","./images/zoomimage.jpg"],
["./excelintegratedreports.html","Excel integrated reports","Overview  Link or bind data from DevMan directly onto MS-Excel to create an integrated report. Use the many features of this popular analytic...","./images/zoomimage.jpg"],
["./expenditure.html","Expenditure","Overview  Achieve a high standard of transparency, plan and track your financials, payments to grantees and for bursaries. Create and refine ...","./images/zoomimage.jpg"],
["./faq.html","Frequently asked questions","Overview  Browse through the FAQ for answers to the most common questions asked by DevMan users. Questions are organised by category with lin...","./images/zoomimage.jpg"],
["./faqcommunication.html","Communication","Topics  This section answers questions related to the different types of communications often asked by DevMan users. DevMan provides the appr...","./images/zoomimage.jpg"],
["./faqemailsmsbroken.html","Troubleshooting - email / sms not working","Enter topic text here.","./images/zoomimage.jpg"],
["./faqgeneral.html","General","Topics  Topics related to system requirements, browsers and internet access.  What are the DevMan system requirements? DevMan is a cost-...","./images/zoomimage.jpg"],
["./faqsearch.html","Find and search","Topics  Questions on surfacing information from finding a single record to basic and advanced search.  Search as you type Search Search ...","./images/zoomimage.jpg"],
["./faqsupport.html","Support","Overview  Assist us to investigate and resolve your requests and complaints or errors correctly and as quickly as possible.  Your clear,...","./images/zoomimage.jpg"],
["./faqvieworgprj.html","How do I view my organisation&#39;s projects","Enter topic text here.","./images/zoomimage.jpg"],
["./fundraising2.html","Fundraising","Overview  Champion your worthy cause by using DevMan&#39;s intuitive fundraising and CRM solution. Automate routine activities, improve your repo...","./images/zoomimage.jpg"],
["./gettingstarted.html","Getting started","Overview  Learn how DevMan works, understand the key concepts and background information. Pick up useful tips and tricks, identify the key ar...","./images/zoomimage.jpg"],
["./grantmanagement.html","Grant management","Overview  Use this module for end-to-end management of your entire grantmaking cycle. Reduce data capture through use of customized online fo...","./images/zoomimage.jpg"],
["./gsysecurity.html","Security","User The term is usually well-known. In the context of The Development Manager program it denotes a person who can \"use\" or is able get ...","./images/zoomimage.jpg"],
["./importsandupdates.html","Imports and updates","Overview  Easily apply a series of changes to a group of records by using the bulk update feature. Updates can be made to people, organisatio...","./images/zoomimage.jpg"],
["./income.html","Income","Overview  Accurate financial records are the lifeblood of your operation. Use the finance module complete with all supporting processes to se...","./images/zoomimage.jpg"],
["./index.html","Introduction","Introduction to Devman3","./images/zoomimage.jpg"],
["./lead.html","Leads","Overview  Use this fundraising tool to track your prospect cultivation, from identification of potential donors through to contract approval ...","./images/zoomimage.jpg"],
["./linking.html","Linking","Link a person, organisation or project  Relationship links can be added and defined between people, organisations and projects.  These c...","./images/zoomimage.jpg"],
["./loggingin.html","Logging in","Overview  A strong login ensures that only authorised users gain access, preventing unauthorised access and potential breaches. Please see Se...","./images/zoomimage.jpg"],
["./mailshot.html","Mailshot","Overview  Mailshots are essential for effective email marketing as well as stakeholder engagement. Connect with your audience, send event inv...","./images/zoomimage.jpg"],
["./meeting.html","Meetings","Overview  Set up meetings and see which projects have been recommended and are on the agenda. Board members can also log in to view this. Add...","./images/zoomimage.jpg"],
["./mergecontacts.html","Merge contacts","Overview  If you have duplicate records of a person or organisation, these need to be merged to combine the history and linked records, such ...","./images/zoomimage.jpg"],
["./navigation.html","Navigation","Overview  To get started with DevMan, please view the step-by-step tutorials below. They outline the main elements you will encounter through...","./images/zoomimage.jpg"],
["./online-updates.html","Online updates","Overview  Contacts can review and update their own contact details directly in DevMan. DevMan provides two ways for contacts to safely update...","./images/zoomimage.jpg"],
["./onlineapplications.html","Online applications","Overview  Cut the administrative burden, take advantage of our online application tool.  Allow your bursary and grants applicants to app...","./images/zoomimage.jpg"],
["./onlinegiving.html","Online giving","Overview  Make giving effortless and simple with DevMan&#39;s integrated online giving portal. Offer donors a fast, easy and secure online giving...","./images/zoomimage.jpg"],
["./onlineresults.html","Online results","Overview  Employ your branded online results page to gather, track and monitor beneficiary submissions.  Topics  Features Bulk gene...","./images/zoomimage.jpg"],
["./organisations.html","Organisations","Overview  Contact details and a profile of your donor, prospect or grantee organisation can be captured here. See how to capture, save and ed...","./images/zoomimage.jpg"],
["./payments.html","Payments","Overview  Capture payments directly for once-off support, or handle via a fuller commitment cycle for grant funding.  Topics  Featu...","./images/zoomimage.jpg"],
["./people.html","People","Overview  This section will assist you to capture, save and edit your contacts&#39; details and profile. Links can be added to other profiles on ...","./images/zoomimage.jpg"],
["./pledges.html","Pledges","Overview   Topics","./images/zoomimage.jpg"],
["./project.html","Projects","Overview  Use this feature to track and report on applications for funding and approved projects. Manage project workflow, financials and doc...","./images/zoomimage.jpg"],
["./projects.html","Projects","Overview  Use this feature to track and report on fundraising causes – referred to as projects in DevMan. Manage fundraising workflow, donati...","./images/zoomimage.jpg"],
["./qualification.html","Qualification and results","Overview  Track your beneficiaries&#39; progress in achieving their qualification.  Use the dashboard for insights on key bursary management...","./images/zoomimage.jpg"],
["./quickguides.html","Product guides","Overview  We&#39;ve provided a number of guides explaining some of the more intricate features and processes on DevMan. These can be used for tra...","./images/zoomimage.jpg"],
["./searching.html","Searching","Overview  Simple and advanced searching tools are available for most DevMan modules to assist with your reporting needs.  Topics  F...","./images/zoomimage.jpg"],
["./searchreport.html","Search &#38; report","Overview  DevMan&#39;s report and analytics platform provides rich search and reporting for all areas. Draw statistical high level summaries and ...","./images/zoomimage.jpg"],
["./section18areceipts.html","Section 18A receipts","Overview  Encourage donor giving by promptly providing any documentation they need for tax benefits available in their country.  Topics ...","./images/zoomimage.jpg"],
["./securityadvanced.html","Advanced","Overview  Secure your data, align DevMan user access with the security protocols in place at your organisation. These topics cover activities...","./images/zoomimage.jpg"],
["./subscription.html","Subscriptions","Overview  Centralise and streamline your communications with stakeholders, identify trends and develop targeted campaigns to generate growth....","./images/zoomimage.jpg"],
["./textmessage.html","SMS","Overview  Take advantage of SMS communication as an efficient way to engage stakeholders, complementing email communications and increasing e...","./images/zoomimage.jpg"],
["./whatsnew.html","What&#39;s new","New features in DevMan  Check your spam score You can now check the spam score and quality of your email templates before hitting send. &#38;nbsp...","./images/zoomimage.jpg"],
["./wip.html","Work in Progress &#38; Notes","If you would like to add steps to this process e.g. project progress reports, go to project life-cycle.","./images/zoomimage.jpg"],
["./workflow.html","Workflow","Overview  Combine DevMan milestones and workflow features to manage key steps, communications, reminders and reporting.  Topics  Fe...","./images/zoomimage.jpg"],
["./xplain/addnewrole.html","Add and edit roles","Add and edit roles",""],
["./xplain/addnewuser.html","Add a new user","Add a new user with the correct persmissions and set an email identity to send emails from.",""],
["./xplain/audittrail.html","User log and audit trail","User log and audit trail - see who changed a record and what details were changed.",""],
["./xplain/batchupdate.html","Update a batch of records","Update a batch of records",""],
["./xplain/bookmarks.html","Bookmarks","Bookmarks - how to add and edit",""],
["./xplain/breadcrumbs.html","Breadcrumbs","Use breadcrumbs to quickly return to pages you had open earlier.",""],
["./xplain/budgetadd.html","Add a budget","Add a budget year",""],
["./xplain/budgetview.html","View a budget","View a budget",""],
["./xplain/bursaryaddnew.html","Add and edit a new bursary","Add and edit a new bursary application.",""],
["./xplain/bursaryprofilepage.html","Bursary profile page","Bursary profile page - a quick overview explaining all the available fields.",""],
["./xplain/bursaryqualificationadd.html","Add a qualification","Add a qualification",""],
["./xplain/bursaryqualificationedit.html","Edit and add results","Edit and add results. Note the many different areas that can be edited in this field.",""],
["./xplain/bursaryqualificationlink.html","Link a qualification to the bursary","Link a qualification to the bursary",""],
["./xplain/bursaryqualificationview.html","View bursary qualifications and results.","View bursary qualifications and results.",""],
["./xplain/bursaryrolloverbulk.html","Bursary - bulk rollover","Bursary - bulk rollover",""],
["./xplain/bursaryrolloverone.html","Bursary - Individual rollover","Bursary - Individual rollover",""],
["./xplain/bursarysearch.html","Search for a bursary","Search for a bursary",""],
["./xplain/bursaryupdatestatus.html","Update bursary status","Update bursary status",""],
["./xplain/cashbookexport.html","Cashbook export","Cashbook export",""],
["./xplain/consentemail.html","Consent email","Consent email - an example of what your contact will receive when requesting consent.",""],
["./xplain/consentrequest.html","Request consent","Request consent",""],
["./xplain/consentupdate.html","Consent status update manually","Consent status update manually",""],
["./xplain/consentview.html","View consent status","View consent status",""],
["./xplain/dashboards.html","Dashboards - predefined","Dashboards explained - transform data sets into analytical snapshots, and view crucial information at a glance.",""],
["./xplain/datagrids.html","Data grids","Data grids - use these versatile features",""],
["./xplain/deleteuser.html","Delete a user","Delete a user",""],
["./xplain/documentupload.html","Upload documents","Upload documents using the upload page",""],
["./xplain/documentview.html","View documents","View documents and edit details.",""],
["./xplain/donationadd.html","Add a new donation","Add a new donation",""],
["./xplain/donorprofilepage.html","Donor profile page","Donor profile page - a quick overview explaining the available fields.",""],
["./xplain/emailverifyaddress.html","Verify sender email address","Verify sender email address",""],
["./xplain/eventaddinvitee.html","Event - add invitees","Event - add invitees",""],
["./xplain/eventaddnew.html","Add a new event","Follow the steps explaining how to add a new event.",""],
["./xplain/eventregistration.html","Event registration module","Event registration module",""],
["./xplain/eventsendinvitation.html","Event - Send the invitation.","View the steps to send an email invitation to an event.",""],
["./xplain/homepage.html","Home page","Home page and navigation",""],
["./xplain/importer.html","Importer","How to use the importer to add invitees to an event or recipients to a mailshot from data saved on an excel spreadsheet.",""],
["./xplain/leadadd.html","Add a lead","Add a lead - add a new lead or approach for funding",""],
["./xplain/leadstatus.html","Update lead status","Update lead status",""],
["./xplain/mailshotaddnew.html","Add a new mailshot","Step by step tutorial on how to create a new mailshot.",""],
["./xplain/mailshotaddrecipient.html","Add mailshot recipients","Step by step tutorial on adding recipients to your mailshot.",""],
["./xplain/mailshotaddtemplate.html","Add a template","Add a template - where do I add a template for my mailshot?",""],
["./xplain/mailshotdocumentlink.html","Add a link to a document","Add a link to a document in your mailshot.",""],
["./xplain/mailshotschedule.html","Schedule a mailshot","Schedule a mailshot - select a time and date when the mailshot will be sent.",""],
["./xplain/mailshotsend.html","Send the mailshot","The final steps to send your mailshot.",""],
["./xplain/mailshotspamcheck.html","Check spam score","Check spam score of your email template before sending",""],
["./xplain/meetingadd.html","Add a meeting","Add a meeting",""],
["./xplain/meetinglinkproject.html","Link projects to a meeting","Link projects to a meeting",""],
["./xplain/menustructure.html","Menu structure","Menu structure",""],
["./xplain/onlineapplications.html","Manage your online applications","Manage your online applications",""],
["./xplain/onlineapplicationsbulkclose.html","Bulk close incomplete applications","Bulk close incomplete applications",""],
["./xplain/onlineapplicationsincomplete.html","Incomplete online applications","Incomplete online applications",""],
["./xplain/onlineapplicationsprint.html","Print application outlines","Print application outlines",""],
["./xplain/onlineapplicationsreopen.html","Re-open an application","Re-open an application",""],
["./xplain/onlineapplicationsresendfailedmail.html","Re-send a failed email","Re-send a failed email",""],
["./xplain/onlinegivingprojectlist.html","Online giving project list","How to manage the online giving project list",""],
["./xplain/organisationaddedit.html","Organisation - add and edit","Organisation - add and edit",""],
["./xplain/passwordchange.html","How do I change my password?","FAQ - How do I change my password?",""],
["./xplain/paymentadd.html","Add a payment","Add a payment",""],
["./xplain/personadd.html","Add and edit a person","Add and edit a person",""],
["./xplain/projectaddnew.html","Add a new project","Add a new project",""],
["./xplain/projectprofile.html","Project profile page","Project profile page",""],
["./xplain/projectsearch.html","Search for a project","Search for a project",""],
["./xplain/projectupdatestatus.html","Update project status","Update project status",""],
["./xplain/questionnairetemplate.html","Questionnaire template","Questionnaire template - how to add questions and create different sets of questions.",""],
["./xplain/resultsgeneratesemester.html","Generate semester","Generate semester",""],
["./xplain/resultssendlink.html","Results - Send link","Send link to upload results",""],
["./xplain/resultsstudentview.html","Online results - Students view","The email request and online portal that the student will see to enter results.",""],
["./xplain/resultsupdatestatus.html","Results - update status","Results - update status",""],
["./xplain/resultsviewsemesters.html","Results - View semesters from Academic results grid","Results - View semesters from Academic results grid",""],
["./xplain/resultsviewsemesterspeople.html","View semesters &#38; monitor results from People","View semesters &#38; monitor results from People using Search advanced",""],
["./xplain/sarsupdatelink.html","SARS self-service update link","SARS self-service update link",""],
["./xplain/search1.html","Search","Search - see all the areas where you can use search.",""],
["./xplain/searchadvanced.html","Search advanced","This powerful tool is available on most DevMan functions, and helps you build reports by adding criteria from multiple data types. See how to use ...",""],
["./xplain/searchsayt.html","Search as you type (SAYT) explained","Search as you type (SAYT) explained",""],
["./xplain/smssend.html","Send SMS","Send SMS to a group of people",""],
["./xplain/subscriptionsview.html","View subscriptions and statistics","View subscriptions and statistics",""],
["./xplain/taxcertificatebulk.html","Bulk generate section 18A receipts","Bulk generate section 18A receipts",""],
["./xplain/taxcertificatecancel.html","Cancel a section 18A receipt","Cancel a section 18A receipt",""],
["./xplain/taxcertificatereissue.html","Reissue a section 18A receipt","Reissue one or more section 18A receipts",""],
["./xplain/taxcertificatesingle.html","Issue a section 18A receipt","Issue a section 18A receipt from a single donation",""],
["./xplain/taxcertificatetemplate.html","Sample s18A receipt template","Sample s18A receipt template",""],
["./xplain/taxdetails2023.html","Tax details 2023","Tax details 2023 - online form for donors to update their tax details that are required by SARS",""],
["./xplain/workflowrule.html","Workflow rule","Application workflow rule - example of how to set up workflow rules",""],
["./yearendrollover.html","Year-end rollover","Overview   Topics  Features Track year-end status of all beneficiaries: Completed - Rollover Completed - Graduated Terminated Manage rol...","./images/zoomimage.jpg"]];
