pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./accountingsystemintegration.htm","Accounting system integration","Accounting system integration Top Previous Next Overview Reduce errors and increase productivity with a single point of entry. DevMan integrates t...",""],
["./actinteraction.htm","Interactions","Interactions Top As interactions are recorded on the system, you are notified in the Weekly activity section of the Home page: You may view these ...",""],
["./actinteractionadd.htm","Add an interaction","Record an interaction Top Add an interaction via communications or contact 1. Click on Communications Interactions Add 2. Open the contact or proj...",""],
["./actinteractionview.htm","View a past interaction","View, edit and print an interaction Top 1.To view a past interaction, search for and select your person, organisation or project. Follow the steps...",""],
["./actionsdue.htm","Actions due","Actions due Top Overview By setting up reminders, you can keep track of which activities are due and which have been completed. Letter reminders a...",""],
["./activitiesinteraction.htm","Activities / Interactions","Activities / Interactions Top Overview As interactions are recorded on the system, you are notified in the Weekly activity section of the Home pag...",""],
["./aftertheevent.htm","After the event","After the event Top Previous Next Overview Topics Features Send follow-up communication such as an event survey. Event status After the event, cha...",""],
["./alumnirollout.htm","Alumni roll-out","Alumni roll-out Top Alumni roll-out You’ve upgraded to Devman to enhance productivity and manage your large Alumni data. Will it benefit you as pr...",""],
["./attachmultifiles.htm","Attach dossier files","Attach dossier files Top For your convenience attaching documents has been made easier with these enhancements: Inline attach mode Attaching more ...",""],
["./attheevent.htm","At the event","At the event Top Previous Next Overview Event registration made simple - use our cutting-edge registration tool to ensure a smooth event experienc...",""],
["./batchupdate.htm","Process a batch of records","Process a batch of records Top Overview Batch or bulk processing is the ability to process multiple (1 - to any number) records at once without te...",""],
["./beforetheevent.htm","Before the event","Before the event Top Previous Next Overview Topics Features Add invitees individually, import them from a spreadsheet or search on DevMan. Apply a...",""],
["./bookmarkmaintenance.htm","Bookmark maintenance","Bookmark maintenance Top Maintenance function where you can make changes to any of your favourites. Change my favourites ",""],
["./breadcrumbbookmarks.htm","Bookmark/Favourites","Bookmark/Favourites Top Speed up the way you move around in Devman by saving links to pages you use often on the home page. This effectively speed...",""],
["./breadcrumbdevman.htm","Breadcrumb in Devman","Breadcrumb in Devman Top Breadcrumbs shows the steps you’ve taken to arrive at a page. ",""],
["./budget.htm","Budget","Budget Top Previous Next Overview Align your budgets with expenditure, use this tool to load your budget before capturing any pledges or payments....",""],
["./bulkprint.htm","Merge and print (batch)","Merge and print (batch) Top Devman has a versatile batch - merge and print feature to supplement the many lists and reports available. Select the ...",""],
["./bulkprint_2.htm","Remove unwanted activities","Remove unwanted activities Top When viewing a project you may at times want to clear out some activities on the detail screen. In this example use...",""],
["./bursary-profile.htm","Bursary profile","Bursary profile Top Previous Next Overview Initiate and solidify connections between students, sponsors and institutions. Provide comprehensive in...",""],
["./bursarymanagement.htm","Bursary management","Bursary management Top Previous Next Overview Transform your bursary management process with configurable, versatile workflow designed to streamli...",""],
["./businessunits.htm","Business units","Business units Top Previous Next Overview DevMan allows you to set up all your business units for an organisation in an easy to see hierarchy usin...",""],
["./canceltaxcertificate.htm","Cancel a tax certificate","Cancel a tax certificate Top Changes may need to be made to the tax certificate such as the date, donor or amount. You will need to first cancel t...",""],
["./cashbookexxport.htm","Cashbook exports","Cashbook exports Top Overview DevMan communicates with your accounting system (such as Pastel). Payments made are transferred into the accounting ...",""],
["./committedgiving.htm","Commitment - giving","Commitment - giving Top Overview Initial take-on: Commitments may be entered manually but are usually imported in batches from spreadsheets. Conta...",""],
["./communication(2).htm","Communications","Communication Top Overview Tips and best practice. This can be simple (adhoc) text or email message or more structured to record important informa...",""],
["./consent.htm","Consent","Consent Top Previous Next Overview Get your POPIA implementation plan off the ground, and painlessly achieve compliance by making practical use of...",""],
["./contactsoverview.htm","Contacts","Contacts Top Overview Your contacts - organisation , person or proposal (project), bursary and the interactions with them are a vital part of your...",""],
["./contract.htm","Contracts","Contracts Top Previous Next Overview Use this feature to manage all your contracts. Upload, store and organise your agreement records for easy acc...",""],
["./dashboardbudget.htm","Dashboard","Dashboard Top When you use Devman budgets you will get helpful dashboards. ",""],
["./debitorders.htm","Debit orders","Debit orders Top Previous Next Overview Drive efficiency, streamline the monthly administration of your debit order donors by using DevMan’s integ...",""],
["./declineproposal.htm","Decline a proposal","Decline a proposal Top Tip Many proposals will be declined without going through any meeting or consideration procedure. This is standard practice...",""],
["./devadministrationmine.htm","Security","Security Top Overview We cannot afford to be complacent or careless about computer security and the safety of the data. Computers and servers are ...",""],
["./devcommunication.htm","Communication","Communication Top Previous Next Overview Engage and build rapport with your audience via channels including email and SMS. Topics Features Manage ...",""],
["./devcontact.htm","Contacts","Contacts Top Previous Next Overview Use this feature to manage all your contacts. These may be linked to other contacts, organisations or projects...",""],
["./devdashboard.htm","Dashboards","Dashboards Top Previous Next Overview Transform data sets into analytical snapshots. View crucial information at a glance. Dashboards are accessib...",""],
["./devfinance.htm","Finance","Finance Top Previous Next Overview DevMan’s financial management component, designed to complement or integrate to your accounting systems is cruc...",""],
["./devhelpfeature.htm","DevHelp features","Using Devhelp in Devman Top Devhelp has changed. Most noticeable is the change in colour from butterscotch and gold to softer blues There&#39;s much m...",""],
["./devmancomponent.htm","DevMan components","DevMan components Top Overview DevMan includes in one comprehensive application the following components usually only found in separate applicatio...",""],
["./devmanfunction.htm","DevMan functions","DevMan functions Top Previous Next Overview Access key features you may need when working with DevMan. It is designed for clear navigation, to be ...",""],
["./devsecurity.htm","Security","Security Top Previous Next Overview Computer security is an important component of a successful organisation. Avoid complacency, control access to...",""],
["./documentmanagement.htm","Document management","Document management Top Previous Next Overview Reduce paper, and increase efficiency with the DevMan dossier (document) upload feature. Topics Fea...",""],
["./donationdepositprocess.htm","Donation deposit process","Donation deposit process Top Previous Next Overview Streamline the monthly administration and allocation of your donations received via direct ban...",""],
["./donations.htm","Donations","Donations Top Previous Next Overview Capture donations directly and if required, send a thank you letter to the donor . Topics Features Link donat...",""],
["./donorengagement.htm","Donor engagement","Donor engagement Top Previous Next Overview Nurture relationships with donors to improve engagement and monitor the various prospect stages. Evalu...",""],
["./donorprofile.htm","Donor profile","Donor profile Top Previous Next Overview The starting point in your cultivation of lifelong relationships with both organisations and individuals....",""],
["./dossier.htm","Dossier","Dossier Top Simplify your admin With DevMan&#39;s dossier feature where you attach any document or file to an activity, organisation, project or conta...",""],
["./email.htm","Email","Email Top Previous Next Overview CRM software gives you the ability to quickly transmit bulk email to your contact lists. This can be very rewardi...",""],
["./emailquicksend.htm","Email quick send","Email someone quickly Top Email someone ",""],
["./emailsendsingle.htm","Send single email","Send single email Top Single email 1.If needed search for the contact (make sure your contact has an email address), tick your selection and click...",""],
["./emailsubscriptionmanagement.htm","Email subscription management","Email subscription management Top WHAT IS IT Devman in collaboration with GraphicMail provides email subscription management. GraphicMail is a lea...",""],
["./entdossierview.htm","View dossier","View dossier Top Once saved, dossiers are kept right inside the database, so never lost, and you may view, change or remove them as required. Find...",""],
["./entitymaintenance.htm","Contact Maintenance","Contact Maintenance Top You may find there are more than one record on Devman for an organisation. What can you do about this? In addition you may...",""],
["./entlink.htm","Linking Contacts","Contact link Top It&#39;s important to know the relationship between persons, organisations and projects. Devman allows for contacts to be linked to e...",""],
["./entlinkcontactview.htm","View or edit links","View a link Top You can see the links between the entity types: Organisations , Projects and Persons . The procedure to view links between the ent...",""],
["./entlinkproject.htm","Linking from a project","Linking from a project Top In the example below we establish a link between project partner (an organisation or person) and the project. All links...",""],
["./entorgprofile.htm","Organisation profile","Organisation profile Top View an organisation profile Once you&#39;ve entered an organisation&#39;s contact information this page allows you to review and...",""],
["./entpersoncontactalter.htm","Alter primary contact","Alter primary contact Top 1. Search for and select the proposal / project and change to \"edit\" mode. Highlight and clear the existing name and ent...",""],
["./entsearchadv.htm","Advanced search","Advanced search Top 1.Click on Search People and organisations Advanced on the Home page. Click here to view 2. To select a group of people or org...",""],
["./eventmanagement.htm","Event management","Event management Top Previous Next Overview Create and manage memorable events, connect and engage with attendees to provide a more personalised e...",""],
["./excelintegratedreports.htm","Excel integrated reports","Excel integrated reports Top Previous Next Overview Link or bind data from DevMan directly onto MS-Excel to create an integrated report . Use the ...",""],
["./expenditure.htm","Expenditure","Expenditure Top Previous Next Overview Achieve a high standard of transparency, plan and track your financials, payments to grantees and for bursa...",""],
["./failedemails.htm","Failed email/sms communications","Failed email/SMS communications Top To re-queue failed email and SMS batches follow these instructions: 1.From the Main DevMan menu select Adminis...",""],
["./faq.htm","Frequently asked questions","Frequently asked questions Top Previous Next Overview Browse through the FAQ for answers to the most common questions asked by DevMan users. Quest...",""],
["./faqbeneficiary.htm","Beneficiary","Beneficiary Top How do I change the status of my beneficiary? Go to Edit beneficiary . How do I see a person&#39;s benefactor? To see a person&#39;s or or...",""],
["./faqcommunication.htm","Communication","Communication Top Previous Next Topics This section answers questions related to the different types of communications often asked by DevMan users...",""],
["./faqcontacts.htm","Contacts","Contacts Top How do I create an employee / employer link? A link is automatically established between an employer and an employee when you choose ...",""],
["./faqdossier.htm","Dossier","Dossier Top Why can&#39;t I open a dossier? It is usually a simple matter to remedy, the dossier file is still safe and secure in the database. The qu...",""],
["./faqemailsmsbroken.htm","Troubleshooting - email / sms not working","Enter topic text here. ",""],
["./faqgeneral.htm","General","General Top Previous Next Topics Topics related to system requirements, browsers and internet access. What are the DevMan system requirements? Dev...",""],
["./faqletter.htm","Letters and templates","Letters and templates Top How do I create a new letter template? When Development Manager was first setup a Kidz representative created a complete...",""],
["./faqlogin.htm","Logging in","Logging in Top Why can&#39;t I log in? You have entered your login name and password and the program does not allow you access. There are several reas...",""],
["./faqpassword.htm","Password","Password Top How do I change my password? Go to \"change my password\" in System administration and settings. ",""],
["./faqpersonorganisationlink.htm","Linking persons to an organisation","Linking persons to an organisation Top Can more than one person be linked to an organisation? Yes it is possible to have more than one person link...",""],
["./faqpopups.htm","Popup blockers","Popup blockers Top What are popup blockers? When trying to print you may encounter the following error: Pop-up windows or advertisements can inter...",""],
["./faqprint.htm","Print","Print Top Previous Next Topics Is there one place with all the print options? No there isn&#39;t - DevMan has many reports and these are accessible wh...",""],
["./faqprintingproblems.htm","Printing &#38; printing problems","Printing &#38; printing problems Top Is there one easy place with all the printing options? No there isn&#39;t and for a good reason but yes it&#39;s quite ea...",""],
["./faqreference.htm","Reference","Reference Top Topics Topics of a general nature, not specific to a particular feature or component. Devman components POPIA bill ",""],
["./faqreports.htm","Reports","Reports Top How do I print a report that includes a graph? A graph can only be displayed on a report that features statistical information. See Pr...",""],
["./faqsearch.htm","Find and search","Find and search Top Previous Next Topics Questions on surfacing information from finding a single record to basic and advanced search. Search as y...",""],
["./faqsecurity.htm","Security","Security Top Previous Next Topics This section answers questions about Internet security and keeping data safe. Security ",""],
["./faqsupport.htm","Support","Support Top Previous Next Overview Assist us to investigate and resolve your requests and complaints or errors correctly and as quickly as possibl...",""],
["./faqvieworgprj.htm","How do I view my organisation&#39;s projects","Enter topic text here. ",""],
["./featuresetting.htm","Feature settings","Feature settings Top DevMan can be configured to suit your organisations&#39; way of working. With this feature you can: Add or remove fields and make...",""],
["./financial.htm","Managing financials","Managing financials Top The management of financials is a core component of both Grantmaking and Fundraising . Whether you are doing grant-making ...",""],
["./financialmanagement.htm","Financials","Financials Top Finance management is a core component of Grantmaking and Fundraising. DevMan process for donations to grantees in CSI and gifts (m...",""],
["./financials.htm","Financials","Financials Top Overview Topics Cashbook exports Donations Section 18A receipts ",""],
["./financials2.htm","Financials","Financials Top Overview Topics Expenditure ",""],
["./financials3.htm","Financials","Financials Top Overview Topics Expenditure ",""],
["./fundraising2.htm","Fundraising","Fundraising Top Previous Next Overview Champion your worthy cause by using DevMan&#39;s intuitive fundraising and CRM solution. Automate routine activ...",""],
["./general-questions.htm","General","General Top What are the DevMan system requirements By far the majority of DevMan clients prefer and accept our more cost-effective cloud-based so...",""],
["./gettingstarted.htm","Getting started","Getting started Top Previous Next Overview Learn how DevMan works, understand the key concepts and background information. Pick up useful tips and...",""],
["./grantmanagement.htm","Grant management","Grant management Top Previous Next Overview Use this module for end-to-end management of your entire grantmaking cycle. Reduce data capture throug...",""],
["./graphic.htm","Graphic","Graphic Top ",""],
["./gsysecurity.htm","Security","User The term is usually well-known. In the context of The Development Manager program it denotes a person who can \"use\" or is able get access to ...",""],
["./importcontacts.htm","Import a list of contacts","Import contacts Top You can import contacts into Devman. Go to Mailshots Bulk imports. Choose email or SMS Import from a spreadsheet and email or ...",""],
["./importsandupdates.htm","Imports and updates","Imports and updates Top Previous Next Overview Easily apply a series of changes to a group of records by using the bulk update feature. Updates ca...",""],
["./income.htm","Income","Income Top Previous Next Overview Accurate financial records are the lifeblood of your operation. Use the finance module complete with all support...",""],
["./inlinecapturemethod.htm","Inline capture method","Inline method Top Inline data entry for reference numbers and dates Inline popup method for multi-select flags ",""],
["./inlinesearch.htm","Inline search","Inline search Top What is the inline search and how do I use it? Inline search - FindAsYouType\" (FAYT) actively searches for words or portions of ...",""],
["./intuitivestatsdisplay.htm","Drill-down on invitee stats","Drill-down on invitee stats Top Event summary ",""],
["./issuetaxcertificate.htm","Issue a tax certificate","Issue a tax certificate Top Search for and select the donation you want to issue, on the donation screen select: Issuing a tax certificate ",""],
["./lead.htm","Leads","Leads Top Previous Next Overview Use this fundraising tool to track your prospect cultivation, from identification of potential donors through to ...",""],
["./letterprintingproblems.htm","Letter printing problems","Letter printing problems Top Printing of letters uses more complex technology than that used to print lists and reports. This is because of the \"M...",""],
["./linking.htm","Linking","Linking Top Previous Next Link a person, organisation or project Relationship links can be added and defined between people, organisations and pro...",""],
["./loggingin.htm","Logging in","Logging in Top Previous Next Topics Why can&#39;t I log in? You have entered your username and password and the program does not allow you access. The...",""],
["./mailshot.htm","Mailshot","Mailshot Top Previous Next Overview Mailshots are essential for effective email marketing as well as stakeholder engagement. Connect with your aud...",""],
["./meeting.htm","Meetings","Meetings Top Previous Next Overview Set up meetings and see which projects have been recommended and are on the agenda. Board members can also log...",""],
["./merge-contacts.htm","Merge Contacts","Merge Contacts Top When you perform a search, you may find that you have two records for the same person or organisation. In order to have good, c...",""],
["./mergecontacts.htm","Merge contacts","Merge contacts Top Previous Next Overview If you have duplicate records of a person or organisation, these need to be merged to combine the histor...",""],
["./navigation.htm","Navigation","Navigation Top Previous Next Overview To get started with DevMan, please view the step-by-step tutorials below. They outline the main elements you...",""],
["./navigation2.htm","Navigation","Navigation Top Topics How to manage bookmarks and favorites, and navigate back to previous page. Navigation ",""],
["./newuser.htm","New users","New users Top When using Development Manager for the first time you may need to make some adjustments to your browser settings. DevMan also allows...",""],
["./online-updates.htm","Online updates","Online updates Top Previous Next Overview Contacts can review and update their own contact details directly in DevMan. DevMan provides two ways fo...",""],
["./onlineapplications.htm","Online applications","Online applications Top Previous Next Overview Cut the administrative burden, take advantage of our online application tool. Allow your bursary an...",""],
["./onlinegiving.htm","Online giving","Online giving Top Previous Next Overview Make giving effortless and simple with DevMan&#39;s integrated online giving portal. Offer donors a fast, eas...",""],
["./onlineresults.htm","Online results","Online results Top Previous Next Overview Employ your branded online results page to gather, track and monitor beneficiary submissions. Topics Fea...",""],
["./organisations.htm","Organisations","Organisations Top Previous Next Overview Contact details and a profile of your donor, prospect or grantee organisation can be captured here. See h...",""],
["./payments.htm","Payments","Payments Top Previous Next Overview Capture payments directly for once-off support, or handle via a fuller commitment cycle for grant funding. Top...",""],
["./people.htm","People","People Top Previous Next Overview This section will assist you to capture, save and edit your contacts&#39; details and profile. Links can be added to...",""],
["./personalpreference.htm","Personal preferences","Personal preferences Top You can personalise DevMan to suit your preferred way of working without affecting other users. Select personal preferenc...",""],
["./personprofilephoto.htm","Add picture","Add picture Top Now you can add a photo with a contact&#39;s details. ",""],
["./printmedia.htm","Print media","Print media Top The program gives you a number of media options to print to. Your choice will be based on your browser settings, and the format yo...",""],
["./printtaxcertificate.htm","Print a tax certificate","Print tax certificates Top ",""],
["./prjbeneficiaries.htm","Project beneficiaries","Project beneficiaries Top By linking beneficiaries to a project, you can track who has benefited from funding received – whether from a bursary, a...",""],
["./prjbeneficiariesadd.htm","Add beneficiary","Add beneficiary Top 1.Search for your project. 2.In the Project profile screen, go to View Links Beneficiaries. Adding beneficiaries 3.Click Add. ...",""],
["./prjbeneficiaryedit.htm","Edit beneficiary","Edit beneficiary Top Beneficiaries of a project can be viewed in a number of different ways, however you can view all of your beneficiaries by yea...",""],
["./prjprojectsummary.htm","Project summary","Project summary Top On a single screen is a summary of an project&#39;s important data including its finances, reminders, interactions, letters, progr...",""],
["./progressreport.htm","Progress reports","Progress reports Top Whether you&#39;re managing a project as a grantor or fundraiser DevMan provides the needed tools for Project Progress Report (PP...",""],
["./project.htm","Projects","Projects Top Previous Next Overview Use this feature to track and report on applications for funding and approved projects. Manage project workflo...",""],
["./projects.htm","Projects","Projects Top Previous Next Overview Use this feature to track and report on fundraising causes – referred to as projects in DevMan. Manage fundrai...",""],
["./proposal.htm","Working with projects and proposals","Working with projects and proposals Top ",""],
["./qualification.htm","Qualification and results","Qualification and results Top Previous Next Overview Track your beneficiaries&#39; progress in achieving their qualification. Use the dashboard for in...",""],
["./quickguides.htm","Product guides","Product guides Top Previous Next Overview We&#39;ve provided a number of guides explaining some of the more intricate features and processes on DevMan...",""],
["./reference.htm","Reference","Reference Top Additional information on varied subjects to assist understanding and make it easier for you to use DevMan more effectively. Topics ...",""],
["./report.htm","Report","Reports and exports Top Whether you&#39;re wanting to print a report or extract and export data there are a few basic steps: 1.First a selection of th...",""],
["./reporting-an-issue.htm","Reporting an issue","Reporting an issue Top Overview Assist us to investigate and resolve your requests and complaints or errors correctly and as quickly as possible. ...",""],
["./reporting-errors.htm","Support protocol","Support protocol Top How do I report an error effectively? Errors are fixed more quickly and more thoroughly with your cooperation and the informa...",""],
["./rptcontact.htm","Printing contact reports","Printing contact reports Top Overview Development Manager provides two menu choices for printing reports: Search (simple) and Search advanced . In...",""],
["./rptcontactenvelope.htm","Envelope printing","Envelope printing Top Overview Topics 1.Options for printing envelopes. Envelope sizes available for printing are: DL, A5, A4 Portrait, A4 Landsca...",""],
["./rptcontactexport.htm","Exporting reports","Exporting reports Top Overview Topics 1.Options for exporting a report. Choose your Export style and click on Export to preview the results. Click...",""],
["./rptcontactlabel.htm","Label printing","Label printing Top Overview Topics 1.Options for printing labels. Click here to view 2.Make your choices, go to Print preview and select from HTML...",""],
["./rptcontactprofiles.htm","Printing contact profiles","Organisation/person contact reports Top Overview Contact information (organisation and person). e.g.: fundraiser will typically view and/or print ...",""],
["./rptcontactreport.htm","Report printing","Report printing Top Overview DevMan provides many reports and \"Report\" menu options are conveniently placed in sub-menus. Topics 1.Options printin...",""],
["./rptproject.htm","Printing project reports","Printing project reports Top 1.Go to Project Print. Click here to view 2.You now need to choose what information you wish to include in your repor...",""],
["./rptprojectlists.htm","Project lists","Project lists Top 1.Once you have selected the records you wish to include in your report and clicked Print (see Printing project reports ), you n...",""],
["./rptprojectlists_2.htm","Project lists_2","Project lists Top 1.Once you have selected the records you wish to include in your report and clicked Print (see Printing project reports ), you n...",""],
["./rptprojectstats.htm","Statistical project reports","Statistical project reports Top 1.Once you have selected the records you wish to include in your report and clicked Print (see Printing project re...",""],
["./rptprojectstats_2.htm","Statistical project reports_2","Statistical finance reports Top 1.Once you have selected the records you wish to include in your report and clicked Print (see Printing project re...",""],
["./rptproject_2.htm","Printing finance reports","Printing finance reports Top 1.Go to Finance Search advanced. 2.You now need to choose what information you wish to include in your report. Projec...",""],
["./rvnbudget.htm","Budgets","Budgets Top Macro Budgets It is important to load your budgets before capturing any pledges or payments. Some budgets are relatively simple, with ...",""],
["./rvnbudgetreport.htm","Print a budget report","Print a budget report Top 1.Go to Finance Budgeting Reports. 2.The Budget summary report will show what funds have been disbursed and what funds a...",""],
["./rvnbudgetview.htm","View a budget","View a budget Top By viewing a budget you can see what funds are still available to be disbursed. 1. To view a budget, go to Finance Budget View. ...",""],
["./rvndonation.htm","Donation","Donation Top Thanking your donors for each gift and issuing tax certificates with very little admin is vital. Devman lets you capture donation dat...",""],
["./rvndonationpledgeadd.htm","Add a pledge","Add a pledge (fundraising) Top Pledges and donations must be allocated to a specific project. If you receive a large number of general donations t...",""],
["./rvndonationpledgepay.htm","Pay a pledge","Pay a pledge (fundraising) Top If you have received money, when adding a donation it is essential to allocate the donation to the pledge, otherwis...",""],
["./rvnpayment.htm","Payments made","Payments made Top Pledges and payments must be allocated to a specific project. When working with large sums of money, we advise that you pledge t...",""],
["./rvnpaymentadd.htm","Add a payment","Add a payment Top If you have pledged money to a project, when making a payment it is essential to allocate the payment to the pledge , otherwise ...",""],
["./rvnpaymentpledgeadd.htm","Add a pledge","Add a pledge (grantmaking) Top The most effective way of managing your budget is to add pledges to your approved projects, especially when working...",""],
["./rvnpaymentpledgepay.htm","Pay a pledge","Pay a pledge (grantmaking) Top If you have pledged money to a project, when making a payment it is essential to allocate the payment to the pledge...",""],
["./rvnpledge.htm","Pledge","Add a pledge (fundraising) Top Pledges - please see \"Commitments\" ",""],
["./savedselections.htm","Saved selections","Saved selections Top Save the selection To create a saved selection: Make your selection with the advanced search Enter a name for the selection i...",""],
["./searching.htm","Searching","Searching Top Previous Next Overview Simple and advanced searching tools are available for most DevMan modules to assist with your reporting needs...",""],
["./searchlookup.htm","Search and lookup","Search and lookup Top Target anyone in your database, view in a dashboard, perform a batch update, bulk communication, export to Excel or print a ...",""],
["./searchreport.htm","Search &#38; report","Search &#38; report Top Previous Next Overview DevMan&#39;s report and analytics platform provides rich search and reporting for all areas. Draw statistic...",""],
["./section18areceipts.htm","Section 18A receipts","Section 18A receipts Top Previous Next Overview Encourage donor giving by promptly providing any documentation they need for tax benefits availabl...",""],
["./securityadvanced.htm","Advanced","Advanced Top Previous Next Overview Secure your data, align DevMan user access with the security protocols in place at your organisation. These to...",""],
["./secuserpermission.htm","Set or change user permissions","Setup/Edit user credentials and permissions Top 1. From Administration - Security - Users - Add for a new user or select from the user list if cha...",""],
["./setpasswordchange.htm","Change password","Change password Top Change my password 1.Select Home My settings Change password. 2.Enter your existing password, and then enter your new password...",""],
["./setting.htm","Settings","Settings Top There are three levels in which Devman can be configured : 1.Feature settings made in the beginning to suit your organisation &#39;s way ...",""],
["./singlerecordlookup.htm","Simple (single record) Lookup","Simple (single record) lookup Top Simple single record lookup When you want to find a single record use the simple search found on each page where...",""],
["./stylesheetfilemanagement.htm","Style-sheet and file management","Style-sheet and file management Top The email style-sheet and graphics file management is conveniently located where you work with email and other...",""],
["./subscription.htm","Subscriptions","Subscriptions Top Previous Next Overview Create effective marketing campaigns. Take advantage of email and SMS automation to connect with your aud...",""],
["./sundry-topics.htm","Sundry topics","Sundry topics Top These are a group of important topics of a general nature and are not specific to a menu. FAQ section Dashboard Search and Look-...",""],
["./taxcertificate.htm","Tax certificates","Tax certificates Top . If you are registered as a PBO you can send tax deductible receipts or tax certificates to donors. Devman provides for the ...",""],
["./template.htm","Communication templates","Communication templates Top The email style-sheet and graphics file management is conveniently located where you work with email and other templat...",""],
["./textmessage.htm","SMS","SMS Top Previous Next Overview Mobile communication is a key platform for stakeholder communication, often used to augment existing email based co...",""],
["./transferdata.htm","Data transfer","Data transfer Top Devman can communicate with your accounting system (such as Pastel). Payments made are transferred from Devman into your account...",""],
["./userguide.htm","User guides","Designed for the less experienced user CSI user Guide Part 1 - Managing projects and proposals Proposals go through a work-flow cycle The basic st...",""],
["./welcometodevman.htm","Introduction","Introduction Top Next Welcome If you are new to DevMan, please consider our Getting started section below. You will find helpful resources which y...",""],
["./whatsnew.htm","What&#39;s new","What&#39;s new? Top Previous Next New features in DevMan Event registration made simple Introducing our cutting-edge registration tool complete with a...",""],
["./wip.htm","Work in Progress &#38; Notes","If you would like to add steps to this process e.g. project progress reports, go to project life-cycle. Reports can be generated from the system a...",""],
["./workflow.htm","Workflow","Workflow Top Previous Overview Combine DevMan milestones and workflow features to manage key steps, communications, reminders and reporting. Topic...",""],
["./workingprocedures.htm","Working procedures","Working procedures Top This section describes the most common basic tasks you will use when working with Devman. Designed as a how-to guide and ar...",""],
["./yearendrollover.htm","Year-end rollover","Year-end rollover Top Previous Next Overview Topics Features Track year-end status of all beneficiaries: oCompleted - Rollover oCompleted - Gradua...",""]];
